Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/environments/staging.rb, config/honeybadger.yml, config/schedule.rb
Work toward #4 
Work toward #5
=> Install honeybadger, capistrano, and whenever

app/models/version_footer.rb, spec/models/version_footer_spec.rb, spec/rails_helper.rb
=> Increases the test coverage analysis to 100% by ensuring that empty classes are ignored, and by extending the test suite for VersionFooter

Gemfile, Gemfile.lock, app/controllers/datasets_controller.rb, app/models/ark.rb, app/models/collection.rb, app/models/dataset.rb, app/models/user.rb, app/views/datasets/index.html.erb, app/views/datasets/show.html.erb, config/environments/development.rb, config/environments/test.rb, config/initializers/ezid_client.rb, config/routes.rb, db/migrate/20220412182528_create_collections.rb, db/migrate/20220412182606_create_datasets.rb, db/schema.rb, db/seeds.rb, lib/tasks/servers.rake, spec/controllers/datasets_controller_spec.rb, spec/factories/user.rb, spec/models/collection_spec.rb, spec/models/dataset_spec.rb
Allows a user to create a new dataset, links the dataset to the user and a default collection, and assigns a new ARK to the dataset.
I created rudimentary Dataset list and show views to allow the process to work through the UI.
I hard coded a couple of sample collections and notes that we want to revisit this to define real default collections (perhaps using the ones in DataSpace )
=> Functionality to creates new datasets and assign a new ARK to them

Gemfile.lock
Needed to fix our ability to deploy.
=> Update Gemfile.lock to reflect current bundler version and platform

app/models/collection.rb, app/models/user.rb, db/migrate/20220414130226_add_default_collection_to_user.rb, db/schema.rb, spec/models/user_spec.rb
Adds support for users to have a default collection.
We currently calculate the default collection based on the department number for the user as reported by CAS.
Part of #28
=> User default collection

README.md, db/migrate/20220421154837_add_column_doi_to_dataset.rb, db/schema.rb, spec/factories/collection.rb, spec/factories/dataset.rb, spec/factories/user.rb, spec/factories/work.rb, spec/models/dataset_spec.rb
Also, set up factories to start mimicking real sample data.
Work toward #71
=> Add DOI to dataset

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, spec/controllers/omniauth_callbacks_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/user.rb, spec/requests/users_spec.rb, spec/system/add_orcid_spec.rb, spec/system/user_edit_spec.rb
=> 60 user routes

app/assets/stylesheets/components/header.scss, app/views/layouts/application.html.erb, app/views/shared/_header.html.erb, app/views/shared/_user_actions.html.erb, app/views/welcome/index.html.erb, spec/requests/welcome_spec.rb
=> 74 user menu

Gemfile, app/controllers/datasets_controller.rb, app/models/s3_file.rb, app/services/s3_query_service.rb, app/views/datasets/show.html.erb, lib/tasks/sample_data.rake, spec/models/s3_file_spec.rb, spec/spec_helper.rb, spec/system/view_data_in_s3_spec.rb
Also: Rake task to create sample data in dev, staging, and production
environments, to make demos easier.
Work toward #71
=> Show S3 files on dataset show page

app/models/user.rb, spec/models/user_spec.rb
=> Better handle the creation of the default UserCollection records

spec/factories/dataset.rb, spec/factories/work.rb, spec/models/work_spec.rb
=> Updated fixtures, fixed broken work spec

app/views/datasets/_form.html.erb, app/views/layouts/application.html.erb
Adds (vertical) tabs to the data entry so that we can handle a large number of sections. We can tweak the actual tabs, but the general idea seems to work.
Closes #115
=> Added vertical tabs skeleton to the edit form.

app/assets/stylesheets/application.css, app/controllers/datasets_controller.rb, app/models/datacite.rb, app/views/datasets/_creators_form.html.erb, app/views/datasets/_form.html.erb, app/views/datasets/_titles_form.html.erb, app/views/users/_form.html.erb, config/routes.rb, spec/controllers/datasets_controller_spec.rb, spec/fixtures/files/datacite_basic.xml, spec/models/datacite_spec.rb
Allows adding more than one title and more than one creator.
Moves #112 and #114 forward.
=> Edit form with Title and Creators

app/controllers/works_controller.rb, app/models/datacite.rb, app/models/work.rb, app/views/works/_creators_form.html.erb, app/views/works/_form.html.erb, app/views/works/_titles_form.html.erb, app/views/works/edit.html.erb, app/views/works/show.html.erb, spec/controllers/works_controller_spec.rb, spec/system/work_spec.rb
Prevents an empty title
Closes #114
=> Title validation

app/views/shared/_header.html.erb, spec/system/accessibility_spec.rb
=> 130 flesh out axe suite

app/models/user.rb, db/migrate/20220608125410_add_family_name_to_user.rb, db/schema.rb, spec/models/user_spec.rb
Removes hardcoded default
Initializes it for existing and new users
=> Adding family name to the user

app/views/works/_edit_javascript.html.erb
Made a few minor enhancements to the code to add creators including making sure they are rendered honoring their order and makes sure the "add me as creator" button uses an existing empty row (if any) instead of always adding a new row.
=> Minor enhancements to the JavaScript

docs/orcid_import.md
Tiny tweak to the Import ORCID documentation
=> Added scp step

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/works/_form.scss, app/controllers/works_controller.rb, app/views/works/_deposit_uploads.html.erb, app/views/works/_deposit_uploads_form.html.erb, app/views/works/_form.html.erb, config/locales/en.yml, spec/controllers/works_controller_spec.rb, spec/fixtures/files/us_covid_2020.csv
=> Ensures that clients can replace individual file uploads as depositors or curators

.gitignore, app/javascript/packs/jquery-ui-triggeredAutocomplete.js, app/models/user.rb, app/views/layouts/application.html.erb, app/views/works/show.html.erb
Adds autocomplete when @mentioning users in the comments
=> Adds autocomplete when @mentioning users in the comments

.tool-versions
=> Upgrading to Node 16

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/works_controller.rb, app/models/work.rb, app/services/active_storage/service/humanized_disk_service.rb, app/views/works/_form.html.erb, config/storage.yml, package.json, spec/controllers/works_controller_spec.rb, spec/models/work_spec.rb, spec/rails_helper.rb, yarn.lock
Advances #110 by ensuring that files stored using the file system can be located by human users
=> Implements a new ActiveStorage service for storing human-readable file names

app/models/work.rb, spec/models/work_spec.rb
=> Ensuring that users can only attach up to 20 file uploads for a given Work

app/services/s3_query_service.rb, config/s3.yml, config/storage.yml, spec/models/work_spec.rb, spec/services/s3_query_service_spec.rb, spec/support/humanizable_storage_specs.rb
=> Integrating the configurations between the S3QueryService and ActiveStorage

architecture-decisions/0001-document-architecture-decisions.md, architecture-decisions/0002-curation-station.md
=> Add ADR documenting storage decisions

.gitignore, config/s3.yml, config/storage.yml, spec/models/work_spec.rb, spec/support/humanizable_storage_specs.rb
=> Ensures that the S3 Bucket ActiveStorage service configurations can be set using environment variables

app/helpers/application_helper.rb, app/views/works/_deposit_uploads.html.erb, app/views/works/_deposit_uploads_form.html.erb, app/views/works/file_upload.html.erb, config/locales/en.yml, spec/views/works/file_upload.html.erb_spec.rb
=> Ensures that multiple file uploads are supported for Works

Gemfile, Gemfile.lock
This will make it easier for us to produce valid DataCite formatted
records, and will let us share the maintanance cost of that with the
California Digital Library.
Work toward #227
=> Add datacite-mapping gem

.rubocop.yml, app/models/valid_datacite.rb, db/migrate/20220808200759_add_datacite_xml_to_work.rb, db/schema.rb, spec/factories/work.rb, spec/models/valid_datacite_spec.rb
We'll then refactor bit by bit to use it,and then we can change the name.
Work toward #227 
@carolyncole Does this give you enough to unblock you on passing datacite during DOI creation? This is going to be a big refactor by the time it's all done and I'm trying to phase it so I'm not sitting on a feature branch for weeks.
=> Build datacite in the ValidDatacite module

package.json, yarn.lock
Upgrading various yarn packages to get security patches and stay
current
=> Yarn upgrades

config/environments/test.rb, spec/rails_helper.rb, spec/system/form_submission_spec.rb
Work toward #261 
Compile assets when running tests in browser.
```
RUN_IN_BROWSER=true be rspec spec/system/form_submission_spec.rb
```
Before: 
After:
=> System spec to test form submission

spec/models/doi_spec.rb
fixes #245
https://doi.test.datacite.org/dois/10.80021%2Ff91s-fg71  - Was updated with the metadata from the fixture when I sent it through the actual api 🎉
=> Updates test to send work xml

app/services/s3_query_service.rb, app/views/works/_deposit_uploads.html.erb, config/environments/production.rb, config/environments/staging.rb, config/s3.yml, config/storage.yml, spec/services/s3_query_service_spec.rb
Make sure we read and use the S3 configuration values in the S3QueryService. Updated the configuration files to have an `amazon` section.
With @carolyncole
=> S3 configuration

Gemfile, Gemfile.lock, app/models/work.rb, app/views/works/show.html.erb, spec/models/work_spec.rb, spec/system/form_submission_spec.rb
refs #207
I do not think this completes the transition to states, as there is still a lot of information in before hooks around save, but it is a first step and everything is still working according to the tests.
=> Adding in the AASM gem and making the work have states

app/views/works/_deposit_uploads_form.html.erb
Fixes a bug in the form rendering when there are indeed files attached to a work. This similar to the fix that we did in PR https://github.com/pulibrary/pdc_describe/pull/283
Fixes #284 
I added a separate issue to update the tests (https://github.com/pulibrary/pdc_describe/issues/286) since that will take a bit more work and I did not want to keep production broken.
=> Fixes bug in Edit form

spec/system/view_data_in_s3_spec.rb
Updated test to look for files managed via Rails ActiveStorage in both the Show and the Edit page. 
This will catch errors like the ones that we fixed in PRs https://github.com/pulibrary/pdc_describe/pull/285 and https://github.com/pulibrary/pdc_describe/pull/283
Closes #286
=> Added test for file uploads rendering

app/controllers/works_controller.rb, app/models/work.rb, app/views/works/_additional_form.html.erb, app/views/works/_creators_form.html.erb, app/views/works/_form_hidden_fields.html.erb, app/views/works/_required_creators_table.html.erb, app/views/works/_required_form.html.erb, app/views/works/_required_title.html.erb, app/views/works/show.html.erb, db/migrate/20220815180808_rename_work_data_cite.rb, db/schema.rb, spec/controllers/works_controller_spec.rb, spec/factories/work.rb, spec/models/doi_spec.rb, spec/models/work_spec.rb, spec/system/accessibility_spec.rb, spec/system/work_spec.rb, spec/views/works/file_upload.html.erb_spec.rb
Renaming accessors and methods also
closes #272
=> Renaming data_cite field to metadata

app/models/work.rb, spec/controllers/works_controller_spec.rb, spec/models/work_spec.rb
Add tests to make sure the transitions occur as desired.
States are diagramed here: https://github.com/pulibrary/pdc_describe/blob/main/docs/work_states.md
=> Adding in all states we have defined

app/models/work.rb, spec/controllers/works_controller_spec.rb, spec/models/work_spec.rb, spec/support/datacite_specs.rb
Sends the update to DataCite
Handles any errors by adding WorkActivities
fixes #196
=> Publishing DOI after approval

app/models/work.rb, spec/models/work_spec.rb
=> Makes sure the DOI minted is saved

app/views/layouts/application.html.erb
=> Adding favicon to show in tab

app/controllers/works_controller.rb, app/models/s3_file.rb, app/models/work.rb, app/services/s3_query_service.rb, spec/controllers/works_controller_spec.rb, spec/models/s3_file_spec.rb, spec/models/work_spec.rb, spec/system/view_data_in_s3_spec.rb
=> Add attachment to rails object when new file in s3

app/controllers/works_controller.rb, app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
Also do not allow precuration files to mess with post curation files
=> Updating to not show directories

app/controllers/works_controller.rb, app/models/work.rb, spec/factories/work.rb, spec/models/pdc_metadata/resource_spec.rb, spec/models/work_spec.rb, spec/system/work_spec.rb
This will keep folks from assigning directly to the metadata field
fixes #277
=> Making work.metadata protected

db/migrate/20220829184502_work_metadata_jsonb.rb, db/schema.rb
=> Changing metadata to be jsonb

.rubocop.yml, app/controllers/works_controller.rb, app/views/works/_files.html.erb, app/views/works/_uploads_form.html.erb, app/views/works/file_upload.html.erb, config/locales/en.yml, spec/controllers/works_controller_spec.rb
=> Ensuring that handling is improved for errors raised during file uploads and provides "delete" buttons for file uploads

spec/factories/work.rb, spec/system/authz_unauthenticated_spec.rb
=> Test that non-authenticated users cannot see or edit works and collections

config/application.rb, config/environments/test.rb
Avoids 'Missing host to link to! Please provide the :host parameter' with PR #375
=> Adding configuration for routes

app/assets/stylesheets/components/works.scss, app/javascript/packs/application.js, app/javascript/packs/vendor/jquery-ui-triggeredAutocomplete.js, app/javascript/packs/works/form.js, app/models/work.rb, app/views/layouts/application.html.erb, app/views/works/_form.html.erb, app/views/works/_uploads_form.html.erb, spec/models/work_spec.rb, spec/system/work_spec.rb
This advances #238 by providing JavaScript-driven rendering and ordering for the upload `<table>` rows within the `Work` form.
=> Prototyping the WorkForm JavaScript functionality, which integrates drag-and-drop reordering support for Work upload <form> <table> row elements

app/models/collection.rb, app/models/work.rb, spec/factories/user.rb, spec/system/authz_admin_spec.rb
=> Test that a collection admin can edit any item in their collection

spec/factories/work.rb, spec/system/authz_admin_spec.rb, spec/system/authz_submitter_spec.rb
=> Test that collection admins can NOT edit collections not their own

app/models/work.rb, spec/system/authz_super_admin_spec.rb
=> Chnaging accepted to approved

app/controllers/works_controller.rb, app/views/shared/_user_actions.html.erb, app/views/users/show.html.erb, app/views/works/_additional_form.html.erb, app/views/works/_form.html.erb, app/views/works/_form_hidden_fields.html.erb, app/views/works/_identifier_form.html.erb, app/views/works/new.html.erb, app/views/works/show.html.erb, spec/controllers/works_controller_spec.rb, spec/system/authz_admin_spec.rb, spec/system/migrate_submission_spec.rb, spec/system/work_spec.rb
This utilizes the edit form to create a dataset on one screen without the wizard mode.
refs #388
=> Adding the ability to Create the Dataset with a DOI

app/controllers/works_controller.rb, app/models/work.rb, app/views/works/_form_hidden_fields.html.erb, app/views/works/_identifier_form.html.erb, config/datacite.yml, config/initializers/load_datacite.rb, spec/factories/work.rb, spec/models/doi_spec.rb, spec/models/work_spec.rb, spec/support/datacite_specs.rb, spec/system/migrate_submission_spec.rb
Converting the ENV references in the code to a config file to make it more consistent with the rest of the configuration Added a url for DOI checking
refs #388
=> Validating DOI based on format and then checking if it exists

spec/controllers/works_controller_spec.rb
When author order is changed in the UI, ensure that change is reflected in the DataCite XML serialization
Fixes #259
=> Test that author order is preserved in DataCite XML

app/models/work.rb, config/datacite.yml, spec/factories/work.rb, spec/system/migrate_submission_spec.rb
Also added test to make sure Arks are updated and Honeybadger is notified if the DOI can not be updated and there is no ARK
fixes #388 
refs #17 Adds as part of the tests to make sure the Ark is updated
=> @carolyncole Adding code to only update DOIs that are part of our prefix

app/controllers/works_controller.rb, app/views/layouts/application.html.erb, app/views/works/index.rss.builder, spec/controllers/works_controller_spec.rb, spec/system/rss_spec.rb
Work toward https://github.com/pulibrary/pdc_discovery/issues/322
=> Add an RSS feed for works, to be used by discovery for indexing

app/controllers/works_controller.rb, app/views/works/index.rss.builder, spec/controllers/works_controller_spec.rb, spec/system/rss_spec.rb
Work toward https://github.com/pulibrary/pdc_discovery/issues/322
=> RSS feed should contain resource json for discovery indexing

app/controllers/works_controller.rb, app/models/work.rb, config/routes.rb, spec/controllers/works_controller_spec.rb, spec/routing/works_routing_spec.rb
=> Supporting DOI and ARK resolution for Works using WorksController#resolve_doi and WorksController#resolve_ark

app/models/work.rb, spec/system/work_upload_s3_objects_spec.rb
This is necessary to fully resolve #386
=> Introduces system RSpec test suites for S3 Object upload for Works

app/assets/stylesheets/application.scss, app/models/collection.rb, app/views/collections/_dataset_table.html.erb, app/views/collections/_edit_javascript.html.erb, app/views/collections/edit.html.erb, app/views/collections/show.html.erb, app/views/users/show.html.erb, spec/system/authz_admin_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/collection_edit_spec.rb
Added the list of datasets to the Collection Show page. Moved the functionality to add submitters and curators to the Edit page.
Below are a few screenshots showing the revamped pages.
Closes #336
=> Collection Show Page

spec/system/work_spec.rb
Doing this before removing the file reordering to make sure it continues to work.
Refs #405
=> Adding a test for creator reordering

app/controllers/works_controller.rb, spec/controllers/works_controller_spec.rb
=> Adds nil check

Gemfile.lock
This version gets the correct url for m1 chips
=> Updating webdrivers

app/assets/stylesheets/application.scss, app/models/pdc_metadata/resource.rb, app/models/pdc_serialization/datacite.rb, app/models/work.rb, app/services/form_to_resource_service.rb, app/views/works/_curator_controlled_form.html.erb, app/views/works/show.html.erb, spec/factories/resource.rb, spec/factories/work.rb, spec/fixtures/files/datacite_basic.xml, spec/system/curator_controlled_metadata_spec.rb
=> Adds version number

app/models/pdc_metadata/resource.rb, app/models/work.rb, app/views/works/_form.html.erb, config/locales/en.yml, spec/controllers/works_controller_spec.rb, spec/models/pdc_metadata/resource_spec.rb
=> Implementing the ResourceType/resourceTypeGeneral metadata properties for the Work deposit form

app/models/pdc_metadata/resource.rb, app/services/form_to_resource_service.rb, app/views/works/_curator_controlled_display.html.erb, app/views/works/_curator_controlled_form.html.erb, spec/controllers/works_controller_spec.rb, spec/models/pdc_metadata/resource_spec.rb, spec/system/curator_controlled_metadata_spec.rb
=> Adding collection tags to the resource

app/models/pdc_metadata/resource.rb, app/services/form_to_resource_service.rb, app/views/works/_additional_form.html.erb, app/views/works/show.html.erb, spec/models/pdc_metadata/resource_spec.rb, spec/system/curator_controlled_metadata_spec.rb
=> Adds support for keywords field

app/views/shared/_user_actions.html.erb, spec/system/authz_admin_spec.rb, spec/system/authz_submitter_spec.rb, spec/system/external_ids_spec.rb
=> Show Create Dataset menu option only to curators

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/works.scss, app/assets/stylesheets/components/works/_form.scss, app/views/works/_curator_controlled_display.html.erb, app/views/works/_curator_controlled_form.html.erb, app/views/works/_required_form.html.erb
This should fully resolve #448
=> Integrating ResourceType and resourceTypeGeneral into the Work forms

app/views/works/show.html.erb, spec/system/work_spec.rb
=> Ensuring that the ResourceType and resourceTypeGeneral attributes are rendered on the Work show view

app/models/work.rb, spec/models/work_spec.rb
=> Ensuring that publishing DOIs can link to PDC Discovery Documents

app/assets/stylesheets/application.scss
=> Fixed header CSS inheritance issue

app/mailers/application_mailer.rb, app/mailers/notification_mailer.rb, app/models/work_activity_notification.rb, app/views/notification_mailer/build_message.html.erb, app/views/notification_mailer/build_message.text.erb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb, spec/factories/work_activity.rb, spec/mailers/notification_mailer_spec.rb, spec/models/work_activity_notification_spec.rb
=> Implementing the NotificationMailer in order to ensure that WorkActivity messages trigger e-mail messages for user accounts

spec/system/work_spec.rb
refs #485
I do not know for sure this will solve #485, but I believe it will.
=> Changing to have_field so that rspec will automatically wait

architecture-decisions/0007-deleteion-of-precurated-files.md
Make sure everyone is aware of what happens when files are deleted from the system. 
fixes #390
=> Adding an ADR for file Deletion

Gemfile, Gemfile.lock
=> Add net-smtp

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_users.scss, app/controllers/users_controller.rb, app/models/user.rb, app/models/work_activity_notification.rb, app/views/users/_form.html.erb, app/views/users/show.html.erb, config/locales/en.yml, db/migrate/20221019171715_add_email_messages_enabled_to_users.rb, db/schema.rb, spec/controllers/users_controller_spec.rb, spec/models/work_activity_notification_spec.rb
=> Extends Users to support disabling e-mail messages for WorkActivityNotification

app/views/works/_edit_javascript.html.erb
- Fix #533
On the issue this was identified as something to pair up for... so I shouldn't have rushed ahead with this. Filing as draft, until there's a good time for a screen share. There are other ways this could be done... for instance, passing in the data structure, and then iterating over it in ERB to build the JSON.
=> Use raw() to inject JSON

app/views/works/_form.html.erb, spec/system/view_data_in_s3_spec.rb
@mccalluc added some comments to a PR that got merge before I could make the suggested changes
=> Updates from PR review

app/views/works/_edit_javascript.html.erb
=> Simplify select menu JS

spec/system/form_submission_spec.rb
=> Adding an automated test for curator notification

app/models/pdc_serialization/datacite.rb, spec/models/pdc_serialization/datacite_spec.rb
=> Add related objects to datacite serialization

spec/fixtures/cytoskeletal_metadata.json, spec/models/pdc_serialization/datacite_spec.rb, spec/system/cytoskeletal_form_submission_spec.rb
=> Add another missing related object to cytoskeletal migration test

app/models/s3_file.rb, app/views/works/uploads/_post_curation_s3_resources.html.erb, config/globus.yml, config/initializers/load_globus.rb, spec/models/s3_file_spec.rb, spec/system/view_data_in_s3_spec.rb
Co-authored-by: Chuck McCallum <mccalluc@users.noreply.github.com>
refs #566
=> Update download link to globus

README.md
Took a little digging to find this, but not confident that it belongs in the readme, either
=> add admin privs to readme

app/assets/javascripts/edit_utils.js, spec/support/orcid_specs.rb, spec/system/work_edit_spec.rb
Fetches ORCID information and dumps it to the right input boxes (creator vs collaborator).
Closes #556
=> ORCID for collaborators/contributors

app/models/pdc_metadata/resource.rb, spec/system/form_submission_spec.rb
=> Do not save a nil related object

app/assets/javascripts/edit_work_utils.js, app/models/pdc_metadata/related_object.rb, app/models/pdc_metadata/resource.rb, app/models/work.rb, app/services/form_to_resource_service.rb, spec/models/pdc_metadata/related_object_spec.rb, spec/models/work_spec.rb, spec/services/form_to_resource_service_spec.rb, spec/system/form_submission_spec.rb
Additionally stop empty resources from the form
=> Validating the related objects

app/views/works/_curator_controlled_form.html.erb, spec/system/curator_controlled_metadata_spec.rb, spec/system/work_edit_spec.rb
Select boxes must be disabled and a hidden field added to return the current value 
fixes #599
=> Select boxes do not respond to readonly

app/models/work.rb, spec/system/authz_admin_spec.rb
Fixes bug in code to fetch works by state to always include the user own works (even if they are an administrator)
Big thanks to @carolyncole for providing the initial test that surfaced the bug.
Fixes #389
=> Fixes bug fetching user's own works

.rubocop.yml, spec/system/flume_form_submission_spec.rb, yarn.lock
Fixes for ticket #491 
redescribed this dataset: https://dataspace.princeton.edu/handle/88435/dsp01qj72pb044?mode=full
```
<?xml version="1.0"?>
<resource xsi:schemaLocation='http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns='http://datacite.org/schema/kernel-4'>
<identifier identifierType='DOI'>10.34770/7hyr-rf67</identifier>
<creators>
<creator>
<creatorName>Ghannam, Khaled</creatorName>
<givenName>Khaled</givenName>
<familyName>Ghannam</familyName>
</creator>
<creator>
<creatorName>Poggi, Davide</creatorName>
<givenName>Davide</givenName>
<familyName>Poggi</familyName>
</creator>
<creator>
<creatorName>Katul, Gabriel</creatorName>
<givenName>Gabriel</givenName> …
```
=> Flume migration spec test

.tool-versions, yarn.lock
production is utilizing 1.22.19, we should be too.
Folks will need to do an `asdf install; yarn install` once this PR is merged to get up to date
=> Updating .tools-version to match the servers

app/controllers/works_controller.rb, app/models/work_activity.rb, spec/controllers/works_controller_spec.rb
=> Ensuring that HTML is sanitized for Comment messages

spec/system/data_migration/cklibrary_form_submission_spec.rb
Validating cklibrary xml against local datacite schema. ticket #603
=> Validate cklibrary xml datacite schema

app/views/works/_work_activity.html.erb, app/views/works/_work_activity_event.html.erb, app/views/works/_work_activity_history.html.erb, app/views/works/show.html.erb, config/application.rb, spec/system/user_show_spec.rb, spec/system/work_edit_spec.rb
- Fix #632
- Add "Unknown user outside the system" failover everywhere
- Factor copy-and-paste code into partial
- Rename partials for clarity
In the test, I don't really understand why the UTC time is offset: I hope that this test doesn't depend on the system timezone.
=> Datestamps in history

spec/system/data_migration/flume_form_submission_spec.rb
Validating flume xml against local datacite schema. ticket #603
=> Validating flume xml datacite schema

spec/system/data_migration/cytoskeletal_form_submission_spec.rb
Validating cytoskeletal xml against local datacite schema. ticket: ticket #603 
This is currently not passing because of a validation bug.
=> Validate cytoskeletal xml datacite schema

app/views/users/edit.html.erb, spec/system/add_orcid_spec.rb, spec/system/user_edit_spec.rb
- Fix #650
... except that this page is also used when an admin is tweaking another user's settings, so "My" could be confusing? I don't have strong feelings one way or the other.
=> "Editing User" -> "My Profile Settings"

app/models/pdc_metadata/resource.rb, app/models/pdc_serialization/datacite.rb, app/services/form_to_resource_service.rb, app/views/works/_additional_form.html.erb, app/views/works/_funder.html.erb, app/views/works/show.html.erb, spec/models/pdc_metadata/resource_spec.rb, spec/models/work_spec.rb, spec/system/work_edit_spec.rb
Adds support for Funder information in the Edit and Show pages as well as in the DataCite serialization.
Closes #497
=> Funder information

app/models/pdc_metadata/rights.rb, spec/system/work_spec.rb
- Replicate #646, but branched from main
- Fix #624
=> Add two OS licenses to the list

app/models/pdc_metadata/title.rb, app/services/resource_compare_service.rb
Plus a slight change to representation of title changes.
- Partial redo of #644, but branched from main
- Prep work for #627
- ... but also see #645: There may be more changes in the future.
=> Refactor to have just one method to compare objects

app/models/pdc_metadata/related_object.rb, app/services/resource_compare_service.rb
- Redo #644, but branching from main
- Fix #627
=> Add related objects to comparison

config/storage.yml
- Complements #712
- Revert accidental config change from #707
=> Add note in storage.yml to explain development against AWS

app/views/works/review.html.erb
=> Change turn-around timeframe from 2-3 to 2-5 business days

app/assets/stylesheets/application.scss, app/views/works/_additional_form.html.erb
=> Use `<details>` wrapper on the keywords field for consistency

.rubocop.yml, app/controllers/users_controller.rb, app/models/pdc_serialization/datacite.rb, app/models/work_activity.rb, app/services/resource_compare_service.rb, config/routes.rb, spec/support/work_s3_requests_specs.rb
=> Loosen the style guidelines in sourcecode, but make the exceptions explicit

app/views/works/_required_form.html.erb, spec/system/work_spec.rb
- Fix #702
... but I'm not super confident that this is the right solution. Is the text ok? Is there a better way to do the default logic?
=> Link to license-picker and make CC-BY the default

app/lib/diff.rb, spec/lib/diff_spec.rb
After the last PR, this was nagging me, but I'm not sure if it's the best course. Feedback welcome.
=> In diffs, shorten strings that are 7 or more words

app/controllers/welcome_controller.rb, app/views/welcome/about.html.erb, config/routes.rb, spec/controllers/welcome_controller_spec.rb
Added route, controller, and view for About page. Text is Lorem Ipsum for now, we can adjust once we have the real text to use.
Closes #541
=> About page (with lorem ipsum text for now)

README.md, config/environments/staging.rb
=> Connecting staging with mailcatcher to allow for testing of mail

.circleci/config.yml
For an example, see https://app.circleci.com/pipelines/github/pulibrary/pdc_describe/2145/workflows/0da664ef-556a-4882-9c92-2441a509c3f7/jobs/6612/artifacts
(That's a separate branch that has its own problems, but I wanted to get this much in.)
=> Capture CI screenshots as artifacts

app/assets/stylesheets/application.scss, app/controllers/users_controller.rb, app/models/work.rb, app/views/users/show.html.erb, config/routes.rb, spec/system/user_show_spec.rb
Adds ability to search for works from the user's dashboard.
Example searches in staging (results might vary depending on your access):
* Find in title: https://pdc-describe-staging.princeton.edu/describe/users/hc8719?q=automeris
* Find in DOI: https://pdc-describe-staging.princeton.edu/describe/users/hc8719?q=+10.80021%2F0hj6-9f47&commit=Search
* Find in contributors: https://pdc-describe-staging.princeton.edu/describe/users/hc8719?q=Sylvia&commit=Search
* Not found: https://pdc-describe-staging.princeton.edu/describe/users/hc8719?q=blahblahblah
Closes #205
=> Adds search to the user's dashboard

config/environments/production.rb
Email successfully sent from production:
=> Adding production smtp configuration

app/views/works/_required_form.html.erb
=> Update rights help text

app/views/works/_additional_form.html.erb
=> Update keyword help text

app/views/works/_funder_table.html.erb
=> Add funder help text

app/views/works/_curator_controlled_form.html.erb
- Fix #755
- Remove wrapping div with inappropriate class
Diff easier to read if [whitespace is hidden](https://github.com/pulibrary/pdc_describe/pull/796/files?diff=unified&w=1).
=> Add help to Curator Controlled page

app/controllers/users_controller.rb, app/models/work.rb, app/models/work_list.rb, spec/models/work_list_spec.rb, spec/models/work_spec.rb
In an effort to not continually add items to the work class this factors out the lists of works into thier on class. 
Also completed test coverage for the different methods
=> Factored out the list of works, which makes the work model smaller.

app/assets/stylesheets/application.scss, app/models/work_activity.rb, app/views/works/_work_activity.html.erb, app/views/works/_work_activity_history.html.erb, app/views/works/show.html.erb, spec/system/work_edit_spec.rb
@hhkitsune should review this and see if the simplified UI is closer to what she wants, and if it is better, what additional tweaks are needed, if any.
Not that there are other PRs in the wings which will also make improvements here:
- #814
- #821 
- #819
before and after:
=> Minimalist UI for prov and messages

spec/system/data_migration/attention_form_submission_spec.rb, spec/system/data_migration/baldwin_form_submission_spec.rb, spec/system/data_migration/bitklavier_form_submission_spec.rb, spec/system/data_migration/bitklavierimage_form_submission_spec.rb, spec/system/data_migration/cklibrary_form_submission_spec.rb, spec/system/data_migration/cytoskeletal_form_submission_spec.rb, spec/system/data_migration/femtosecond_form_submission_spec.rb, spec/system/data_migration/flume_form_submission_spec.rb, spec/system/data_migration/sowingseeds_form_submission_spec.rb
=> licenses change

app/assets/javascripts/edit_work_utils.js, spec/system/work_create_spec.rb
=> In the select options, only show contributor roles that are apply to individual contributors

spec/system/authz_submitter_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/data_migration/attention_form_submission_spec.rb, spec/system/data_migration/baldwin_form_submission_spec.rb, spec/system/data_migration/bitklavier_form_submission_spec.rb, spec/system/data_migration/bitklavierimage_form_submission_spec.rb, spec/system/data_migration/cklibrary_form_submission_spec.rb, spec/system/data_migration/cytoskeletal_form_submission_spec.rb, spec/system/data_migration/femtosecond_form_submission_spec.rb, spec/system/data_migration/flume_form_submission_spec.rb, spec/system/data_migration/sowingseeds_form_submission_spec.rb, spec/system/external_ids_spec.rb, spec/system/migrate_submission_spec.rb, spec/system/work_create_spec.rb, spec/system/work_spec.rb
Some tests were continuously failing on my machine.  It may be because my machine is a bit faster. 
In general it is better to utilize the rspec methods over find as they will delay until the page fully loads
I also find it easier to understand which option is being chosen
=> Change find to select to allow the test to wait

app/models/pdc_metadata/resource.rb, app/models/pdc_serialization/datacite.rb, app/models/work.rb, docs/test_data_in_production.md, lib/tasks/works.rake, spec/factories/work.rb, spec/models/doi_spec.rb, spec/models/pdc_metadata/resource_spec.rb, spec/models/pdc_serialization/datacite_spec.rb, spec/models/work_spec.rb
Also rename hash to jsonb_hash to more accurately represent what is being passed as a parameter
fixes #802
=> Rename json to jsonb to more accurately represent what the method is doing

app/assets/javascripts/edit_work_utils.js, app/models/pdc_metadata/funder.rb, app/models/pdc_serialization/datacite.rb, app/services/form_to_resource_service.rb, app/views/works/_funder_table.html.erb, spec/fixtures/resource-to-datacite/basic.datacite.xml, spec/fixtures/resource-to-datacite/basic.resource.yaml, spec/fixtures/resource-to-datacite/old.datacite.xml, spec/models/pdc_metadata/resource_spec.rb, spec/models/work_spec.rb
- Fix #729
Notes:
- This does not add any system tests for the API call. It could.
- This does not add any server-side validation: It could... Would we we want to just check the regex? or hit the API and make sure the ID resolves? or Make sure the ID is in sync with the name?
- I made a change to make the changelog for this field more readable... but it doesn't seem to show up at all. Filed  #867.
=> Allow Funder ROR to be supplied

app/views/works/_work_activity_messages.html.erb, app/views/works/_work_activity_provenance.html.erb, app/views/works/show.html.erb
- Prep work for #823
- In #857 I'm working on adding more testing to this view code.
=> split work_activity_history partial

Gemfile, Gemfile.lock, README.md, config/environments/development.rb
Derived from https://github.com/pulibrary/pdc_describe/pull/853, please see https://github.com/pulibrary/pdc_describe/pull/853#discussion_r1073687851 for the specific context.
=> Setting MailCatcher as the default Mail setup for the development environment

app/views/works/attachment_select.erb, spec/system/work_create_spec.rb
=> Updating page text to be 100MB instead of 100GB

spec/system/data_migration/bitklavierimage_form_submission_spec.rb
=> Updating bitklavier image migration test to fill in collection tags

app/models/s3_file.rb, spec/models/s3_file_spec.rb
Allows globus url to work if the file name has a space fixes #892
=> URL encoding the globus file name

README.md, app/views/works/_work_activity_provenance.html.erb, config/initializers/load_provenance_message_writers.rb, config/provenance_message_writers.yml, docs/how_to_add_postdated_provenance.md
- Fix #849
That issue specifies the implementation, but as I re-read it, it also proposes to combine this with admin privs. I don't care strongly which approach is taken.
- This with have a merge conflict with #857: That is older and more complicated, so I'd prefer to get that reviewed and merged before this.
=> Move hard-coded list of users out of ERB and into configuration; Add documentation

app/controllers/welcome_controller.rb, app/views/welcome/license.html.erb, app/views/works/_license_text.html.erb, app/views/works/review.html.erb, config/routes.rb, spec/controllers/welcome_controller_spec.rb, spec/system/license_spec.rb, spec/system/work_create_spec.rb
Also change the work license to a partial so we can reuse it in welcome fixes #897
=> Adding a license page to the welcome controller

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_container.scss, app/views/works/_work_activity_messages.html.erb, app/views/works/show.html.erb, spec/system/work_create_spec.rb
- Fix #823 
I'm a little uncomfortable with more ad-hoc jquery, but I think this is what is requested.
Defaults to open:
Can be closed:
=> Move messages up to sidebar on the right which can be toggled

docs/monitoring.md
refs https://github.com/pulibrary/rdss-handbook/issues/99
blocked by https://github.com/pulibrary/rdss-handbook/pull/109
=> Adding Monitoring document to pdc_describe

app/assets/stylesheets/application.scss, app/views/works/_additional_form.html.erb, app/views/works/_contributors_table.html.erb, app/views/works/_funder_table.html.erb, app/views/works/_related_objects_table.html.erb, app/views/works/_required_creators_table.html.erb, app/views/works/_required_form.html.erb, app/views/works/_required_title.html.erb
- Fix #909
On these two pages: 
- Add consistent wrapping divs
- Settle on no-colon for consistency
- Reduce the size of the column headers and the "add additional..." buttons
=> Improve formatting of data entry pages

app/helpers/application_helper.rb, app/views/works/_orcid_link.html.erb, app/views/works/show.html.erb, spec/system/work_spec.rb
=> Clean up utility code to avoid JS injection

spec/system/data_migration/baldwin_form_submission_spec.rb, spec/system/data_migration/bitklavier_form_submission_spec.rb, spec/system/data_migration/bitklavierimage_form_submission_spec.rb, spec/system/data_migration/cklibrary_form_submission_spec.rb, spec/system/data_migration/cytoskeletal_form_submission_spec.rb, spec/system/data_migration/flume_form_submission_spec.rb
change code to "additional metadata" instead of the "v-pills-additional-tab"
change code to "Curator Controlled" instead of "v-pills-curator-controller-tab"
=> changed vpill code in migration specs to Additional Metadata and/or Curator Controlled

config/provenance_message_writers.yml
=> Add Hannah to prov note users

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
Adds in pagination to the AWS S3 query service to allow as many files as exists to be loaded.
fixes #938
=> Allowing system to retrieve more than 1000 files per work

app/assets/config/manifest.js, app/javascript/entrypoints/pdc/copy_to_clipboard.es6, app/javascript/entrypoints/pdc/pdc_ui_loader.es6, app/views/works/show.html.erb
Basically copied and pasted the code, converted it to es6, and wrapped it in a class
=> Moving DOI copy to clipboard into Vite managed class

README.md
- proposed fix #888
We discussed this a little a week or two back, and I thought just drafting a message would be a start. If this isn't the right tone, or someone else owns it, or we just don't need it, feel free to close.
=> Explain the limitations of this software in the README

app/assets/javascripts/edit_work_utils.js, app/models/pdc_metadata/name_identifier.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, spec/models/pdc_metadata/name_identifier_spec.rb, spec/support/external_identifier_specs.rb, spec/system/data_migration/femtosecond_form_submission_spec.rb
=> Mock ROR integration so we can test it

app/controllers/work_downloader_controller.rb, config/routes.rb, spec/requests/work_downloader_spec.rb, spec/routing/works_routing_spec.rb
Creates a presigned url and redirects if the user has access to the work
fixes #982
=> Create a route for downloading from AWS

app/controllers/works_controller.rb, app/models/s3_file.rb, app/views/works/uploads/_pre_curation_s3_resources.html.erb, spec/models/s3_file_spec.rb, spec/system/view_data_in_s3_spec.rb
Display filename without DOI/ID prefix. Display file size with commas (but sorts based on integer value).
Moves forward #986
=> Pre-curated file list display improvements

app/models/s3_file.rb, app/views/works/uploads/_pre_curation_s3_resources.html.erb, spec/system/view_data_in_s3_spec.rb
* Last modified is display in the EST time zone and in human readable form
* Last modified is sortable (uses yyyy-mm-dd hh:mm value)
* Restores the "download" icon 
Closes 986
=> File list display enhancements

config/routes.rb, spec/routing/users_routing_spec.rb
=> Fixes problem accessing User Edit for guest account

spec/system/data_migration/sowingseeds_form_submission_spec.rb
fixed formatting in sowing seeds spec
=> fixed formmatting issue in description for sowingseeds spec

app/controllers/works_controller.rb, app/services/s3_query_service.rb, spec/controllers/works_controller_spec.rb, spec/services/s3_query_service_spec.rb, spec/support/s3_query_service_specs.rb
=> Creating a folder in Amazon so the curators do not need to do it by hand

app/models/s3_file.rb, app/models/upload_snapshot.rb, app/models/work.rb, db/migrate/20230303165757_create_upload_snapshots.rb, db/schema.rb, spec/factories/upload_snapshot.rb, spec/models/s3_file_spec.rb, spec/models/upload_snapshot_spec.rb, spec/models/work_spec.rb
=> Implementing the models for snapshots of ActiveStorage attachments (uploads of Works)

app/views/works/_funder_table.html.erb
=> Move ROR to the end of the funder table

app/assets/stylesheets/application.scss, app/controllers/works_controller.rb, app/views/works/_wizard_progress.html.erb, app/views/works/attachment_select.erb, app/views/works/file_cluster.html.erb, app/views/works/file_other.html.erb, app/views/works/file_upload.html.erb, app/views/works/readme_select.html.erb, app/views/works/review.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/works_controller_spec.rb, spec/routing/works_routing_spec.rb, spec/system/authz_submitter_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/external_ids_spec.rb, spec/system/work_create_spec.rb
Will need continued work to make the README Required.
refs #996
=> Added README step to the system.

app/views/works/readme_select.html.erb
=> Allow README instructions to open in a new tab

app/controllers/works_controller.rb, app/models/readme.rb, app/services/s3_query_service.rb, spec/controllers/works_controller_spec.rb, spec/factories/s3_file.rb, spec/fixtures/files/readme_template.txt, spec/models/readme_spec.rb, spec/services/s3_query_service_spec.rb, spec/support/s3_query_service_specs.rb, spec/system/authz_submitter_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/external_ids_spec.rb, spec/system/work_create_spec.rb
Added a Readme class to help with the logic
=> Made the README required

app/controllers/works_controller.rb, app/javascript/entrypoints/pdc/pdc_ui_loader.es6, app/javascript/entrypoints/pdc/readme_file_upload.es6, app/models/readme.rb, app/views/works/readme_select.html.erb, spec/controllers/works_controller_spec.rb, spec/models/readme_spec.rb, spec/system/work_create_spec.rb
Also shows existing README on page if one has already been selected 
fixes #966
=> Adding Javascript to require README

app/models/work.rb
Fixes https://github.com/pulibrary/pdc_describe/issues/1064
=> Make publishing a DOI nil-safe

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
Changing all copies to multipart so that we can handle files larger than 5GB during publish and other AWS file movements
Specifically this will be needed for files that are in Dspace that were uploaded to Globus, because some of them are larger than 5GB.  The example  https://dataspace.princeton.edu/handle/88435/dsp01s7526g63n has this issue.
refs #1019
=> Moving away from copy_object as that is limited to 5GB files

app/jobs/dspace_file_copy_job.rb, app/services/pul_dspace_data.rb, app/services/s3_query_service.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/s3.yml, lib/tasks/dspace.rake, spec/fixtures/files/dspace_metadata_response.json, spec/jobs/dspace_file_copy_job_spec.rb, spec/services/pul_dspace_data_spec.rb, spec/services/s3_query_service_spec.rb
Adding a Job to copy a file from Globus AWS bucket to PDCDescribe AWS Bucket 
Adding the ability to queue all the jobs in the PULDspaceDataService 
Updated the rake task to utilize the new migrate method in PULDspaceDataService
fixes #1019
=> Adding the copying of files from the Dspace AWS to the PDC AWS

app/services/pul_dspace_data.rb, app/views/works/show.html.erb
Fixes https://github.com/pulibrary/pdc_describe/issues/1078
Also fixes this:
=> Small fixes to DataSpace migration service

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
=> Updating pagination of file listing to allow for dspace bucket and prefix

.circleci/config.yml, .tool-versions, Gemfile, Gemfile.lock, spec/rails_helper.rb
@kayiwa updated to run on Ruby 3.1.0
=> Jammy update

app/views/works/show.html.erb
=> Changed label Creator to Depositor

spec/system/data_migration/hybrid_drift_form_submission_spec.rb, spec/system/data_migration/thomson_scattering_form_submission_spec.rb
Advances:
* https://github.com/pulibrary/pdc_discovery/issues/355
=> Fixes to PPPL migration specs

package.json, yarn.lock
Unsure why I need them, but not others.  We should try deploying to be certain this does not cause other issues
```
[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /Users/colec/projects/pdc_describe/app/javascript): [Error] Cannot find module 'postcss-import'
Require stack:
- /Users/colec/projects/pdc_describe/postcss.config.js
Error: Cannot find module 'postcss-import'
Require stack:
- /Users/colec/projects/pdc_describe/postcss.config.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> …
```
=> Updates required by my laptop to run vite

.circleci/config.yml, lib/simplecov_helper.rb, lib/tasks/simplecov.rake, spec/rails_helper.rb
=> Ensuring that coveralls is replaced with just simplecov

Gemfile, Gemfile.lock
Also added ed25519 to allow for deploying with newer keys
fixes https://github.com/pulibrary/princeton_ansible/issues/3848
=> Allowing simplecov to be run on the servers

app/models/work.rb
This ensures that `WorkActivity` models for `UploadSnapshots` consistently contain multiple actions tracking file modifications.
=> Ensuring that only a single WorkActivity with multiple events will be created for file additions, replacements, and deletions

app/jobs/dspace_file_copy_job.rb, app/services/pul_dspace_data.rb, app/services/s3_query_service.rb, spec/jobs/dspace_file_copy_job_spec.rb, spec/services/pul_dspace_data_spec.rb, spec/services/s3_query_service_spec.rb
Allowing directories to be returned from S3QueryService to implement this Added Copy directory to S3QueryService need to add in tests
fixes #1100
=> Have PULDspaceData copy directories and files

app/models/work.rb, spec/controllers/works_controller_spec.rb, spec/factories/work.rb, spec/models/s3_file_spec.rb, spec/models/work_spec.rb, spec/system/migrate_submission_spec.rb
Also change the factory to create a random doi so they do not conflict 
Updating a few tests that depended on the old hard coded doi
refs #1062
=> Checking to make sure the DOI is unique

app/models/work.rb, spec/models/work_spec.rb, spec/services/resource_compare_service_spec.rb, spec/system/migrate_submission_spec.rb
Updating a few tests that created works with the same ARK
Also fixed a bug with unique to not count itself if it has been saved as a conflict with being unique
fixes #1062
=> Checking to make sure the ARK is unique

db/migrate/20230503142628_snapshot_uri.rb, db/schema.rb
=> Add migration to rename UploadSnapshot uri to url

lib/tasks/works.rake
Adds rake task to help troubleshoot records with bad DataCite attributes.
Used to troubleshoot #1129
=> Rake task for DataCite validation 

Gemfile, Gemfile.lock, app/models/work.rb, app/presenters/work_presenter.rb, app/views/works/show.html.erb, spec/presenters/work_presenter_spec.rb, spec/requests/works_spec.rb, spec/system/work_show_spec.rb
=> Integrates Rinku for rendering links as markup within Work metadata

spec/system/data_migration/non_axisymmetric.xml, spec/system/data_migration/non_axisymmetric_form_submission_spec.rb
Advances:
* https://github.com/pulibrary/pdc_describe/issues/1145
=> Fix title in migration fixture

app/jobs/dspace_file_copy_job.rb, spec/models/migration_upload_snapshot_spec.rb
☝️ See the migration line in the provenance!!
=> Adding a transaction to MigrationUploadSnapshot to allow for multiple  threads processing jobs

app/views/groups/index.html.erb, db/seeds.rb, lib/tasks/users.rake, lib/tasks/works.rake, spec/controllers/works_controller_spec.rb, spec/models/collection_spec.rb, spec/models/work_list_spec.rb, spec/services/s3_query_service_spec.rb, spec/system/authz_submitter_spec.rb, spec/views/works/file_upload.html.erb_spec.rb
Also removes the collection_cleanup rake task
=> Replacing all Collection. calls with Group. calls

app/controllers/works_controller.rb, app/models/group_option.rb, app/models/user.rb, db/migrate/20230517124232_rename_collection_to_group.rb, db/schema.rb, spec/factories/user.rb
Additionally renamed the default_collection_id in user to default_group_id
=> Change GroupOption table to be group_options instead of collection_options

app/controllers/works_controller.rb, app/models/group.rb, app/models/work.rb, app/models/work_list.rb, app/views/works/_curator_controlled_form.html.erb, db/migrate/20230517183649_rename_collections_to_groups.rb, db/schema.rb, spec/controllers/works_controller_spec.rb, spec/models/work_list_spec.rb, spec/models/work_spec.rb, spec/services/form_to_resource_service_spec.rb, spec/system/accessibility_spec.rb, spec/system/authz_admin_spec.rb, spec/system/work_create_spec.rb, spec/system/work_edit_spec.rb, spec/views/works/file_upload.html.erb_spec.rb
Also renaming the work collection_id column to group_id
=> Renaming the collections table to groups

docs/work_states.md
Also change Curator to moderator and tombstone to deletion marker
refs #1171
refs #1030
=> Updating the work state diagram to have group instead of collection

app/models/work.rb, lib/tasks/works.rake, spec/controllers/works_controller_spec.rb, spec/models/work_spec.rb
=> Renaming collection in json output to group

spec/system/data_migration/spindle.xml, spec/system/data_migration/spindle_form_submission_spec.rb
=> migration spec for sleep spindle refractoriness

app/services/pul_dspace_migrate.rb
This was missed when I changed the variables to instance variables
@jrgriffiniii pointed this out in the [PR review](https://github.com/pulibrary/pdc_describe/pull/1199).  It was a good point, so I implemented it.
=> Updating to not pass instance variable

app/services/pul_dspace_connector.rb, spec/services/pul_dspace_connector_spec.rb
=> Adding a better error message when bitstreams do not pass checksum test

app/controllers/work_migration_controller.rb, app/services/pul_dspace_migrate.rb, spec/services/pul_dspace_migrate_spec.rb
=> Checking for dspace checksum error before creating migration snapshot

Gemfile, Gemfile.lock, config/initializers/datadog.rb
=> Add log injection for datadog to enable log tracing

app/models/work.rb, spec/models/work_spec.rb
=> Adding validation to disallow empty DOIs during approval

.circleci/config.yml, app/jobs/attach_file_to_work_job.rb, app/models/work.rb, app/models/work_activity.rb, app/services/work_uploads_edit_service.rb, spec/controllers/works_controller_spec.rb, spec/models/work_activity_spec.rb, spec/models/work_spec.rb, spec/rails_helper.rb, spec/requests/works_spec.rb, spec/services/work_upload_edit_service_spec.rb, spec/system/data_migration/attention_form_submission_spec.rb, spec/system/work_comment_spec.rb, spec/system/work_edit_spec.rb
=> Ensuring that file uploads are asynchronous

app/assets/javascripts/edit_work_utils.js, app/javascript/entrypoints/pdc/edit_orcid.es6, app/javascript/entrypoints/pdc/pdc_ui_loader.es6
refs #959
Making javascript more compartmentalized before I add in ROR
=> Moving orcid javascript into vite

app/assets/javascripts/edit_work_utils.js, app/javascript/entrypoints/pdc/pdc_ui_loader.es6, app/javascript/entrypoints/pdc/work_orcid.es6, app/services/form_to_resource_service.rb, app/views/works/_individual_contributors_table.html.erb, spec/system/data_migration/bitklavier_form_submission_spec.rb, spec/system/work_create_spec.rb, spec/system/work_edit_spec.rb, spec/system/work_spec.rb
Moving the HTML out of javascript and into the views. This matches the funder and creator tables.
refs #959
=> Changing the contributor table to match the funder and creator style

app/assets/javascripts/edit_work_utils.js, app/services/form_to_resource_service.rb, app/views/works/_related_objects_table.html.erb, spec/services/form_to_resource_service_spec.rb, spec/system/data_migration/cytoskeletal_form_submission_spec.rb, spec/system/data_migration/hybrid_drift_form_submission_spec.rb, spec/system/data_migration/ion_orbital_form_submission_spec.rb, spec/system/data_migration/non_axisymmetric_form_submission_spec.rb, spec/system/data_migration/observation_axisymmetric_form_submission_spec.rb, spec/system/data_migration/thomson_scattering_form_submission_spec.rb, spec/system/work_create_spec.rb, spec/system/work_edit_spec.rb
This pattern utilizes less javascript and more HTML for creating the tables
=> Moving Related object table to match funder, creator, and contributor pattern

app/views/works/readme_select.html.erb, config/locales/en.yml
We did not yet add the additional section describing a Readme
refs #1226
=> Updated the existing text on the Readme to match the new desired text

app/assets/javascripts/edit_work_utils.js, app/models/pdc_metadata/affiliation.rb, app/models/pdc_metadata/creator.rb, app/models/pdc_serialization/datacite.rb, app/services/form_to_resource_service.rb, app/views/works/_required_creators_table.html.erb, spec/models/pdc_metadata/affiliation_spec.rb, spec/models/pdc_metadata/creator_spec.rb, spec/models/pdc_serialization/datacite_spec.rb, spec/system/work_spec.rb
=> Adding ROR and affiliation fields to the creator form and different serializations

app/views/works/_required_creators_table.html.erb
Add required marker to given name and family name
refs #959
=> Add table headers for Affiliation and ROR

app/models/work.rb, config/initializers/load_manual_dataspace_migration.rb, config/manual_dataspace_migration.yml, spec/models/work_spec.rb
=> Configuration for allowing some objects to skip DataSpace download

app/services/pul_dspace_migrate.rb, spec/services/pul_dspace_migrate_spec.rb
=> Generate migration snapshots for manually migrated DataSpace objects

README.md, config/deploy.rb
=> Add capistrano task to open sidekiq console

app/controllers/works_controller.rb, app/models/work.rb, spec/controllers/works_controller_spec.rb
Optimize the code that produces the JSON file list for a work to prevent it from nesting the work itself for everyfile on the list.
Closes #1156
=> Optimizes the file list generation

app/services/pul_dspace_migrate.rb, spec/services/pul_dspace_migrate_spec.rb
=> Improve message about Globus only migration

app/services/pul_dspace_migrate.rb
Advances #1215 
Fixes this bug:
=> Create MigrationUploadSnapshot before firing off DspaceFileCopyJob

app/models/s3_file.rb, app/models/work.rb, app/views/works/_s3_resources.html.erb, spec/models/work_spec.rb, spec/system/authz_submitter_spec.rb
=> Adding display size to s3 file and displaying that in the views

app/jobs/attach_file_to_work_job.rb, spec/controllers/works_controller_spec.rb, spec/services/work_upload_edit_service_spec.rb
=> Removing active storage call for upload and replace it with a direct call to AWS S3

app/views/works/readme_select.html.erb
=> Add the Readme definition section to the Readme selection page

app/controllers/users_controller.rb, app/views/users/index.html.erb, spec/requests/users_spec.rb, spec/system/user_show_spec.rb
=> Display basic information about users in the Users List page

app/javascript/entrypoints/pdc/edit_table_actions.es6, app/views/works/_required_creators_table.html.erb, spec/factories/user.rb, spec/system/work_create_spec.rb
Also, fix bug in finding empty row
Added a test so these will be caught if they break in the future
fixes #1251
=> Change the affiliation class so that the last name does not get filled in as the affiliation

app/views/works/new_submission.html.erb, spec/controllers/works_controller_spec.rb
=> Prevents developer comment from showing to the user.

docs/smoke_test.md
First pass at documenting our smoke test process
Moves #1275 forward
=> Document manual script to test the system (smoke test)

s3-checksum.yaml
The original script was [here](https://github.com/aws-samples/amazon-s3-checksum-verification/blob/main/s3-checksum.yaml) but it just created new versions for ever, becuase it's test for existing checksum was broken 
Also it did not handle files with spaces
Refs #1223
=> Adding a working SHA256 lambda script

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_nav.scss, app/assets/stylesheets/components/_users.scss, app/assets/stylesheets/components/header.scss, app/views/shared/_admin_actions.html.erb, app/views/shared/_header.html.erb, app/views/shared/_user_actions.html.erb
=> Color and nav changes

README.md
Advances https://github.com/pulibrary/pdc_describe/issues/409
=> Documentation about how to add migration staff

config/update_ark_url.yml
Advances https://github.com/pulibrary/pdc_describe/issues/409
=> Update ARKs in production

config/initializers/ezid_client.rb, config/update_ark_url.yml
Advances https://github.com/pulibrary/pdc_describe/issues/409
=> Fix ezid creds

app/models/work.rb, config/update_ark_url.yml
=> Update ark with discovery url

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
=> Adding sha256 on copy from pre-curation to post-curation

app/views/works/_required_title.html.erb
=> Removing the &mdash; typo

app/views/welcome/how_to_submit.html.erb
=> Updated submission info

app/assets/stylesheets/application.scss, app/views/welcome/how_to_submit.html.erb
=> Improved offset for submit ordered list block

app/views/shared/_admin_actions.html.erb
There was a warning during the rspec test about this duplicate class.  Just decided to clean it up
=> Remove duplicate class specification

app/views/works/_required_creators_table.html.erb, spec/system/work_spec.rb
=> Move the ORCID after the Given and Family Name

app/views/works/_s3_resources.html.erb, spec/system/work_show_spec.rb
=> Ensuring that the DataTables jQuery plugin is consistently bound to the DOM between page navigation operations

app/models/work.rb
We are no storing our files via AttachFileToWorkJob
=> Removing save of pre_curation_uploads since we no longer utilize them

docs/how_to_delete_a_work.md, lib/tasks/works.rake
Becuase pre_curation_uploads is not getting updated any more we need to utilize pre_curation_uploads_fast instead
=> Update instructions and rake task to not use pre_curation_uploads

app/assets/stylesheets/application.scss, app/views/works/_curator_controlled_form.html.erb, app/views/works/_required_creators_table.html.erb, app/views/works/_required_form.html.erb, app/views/works/_required_form_field_details.html.erb, spec/system/work_spec.rb
We made the start 1.5 em since that seemed to match with the change in the ticket.
Additionally fixes a bug in the work_spec where the new ROR was not included in the bi directional second drag, so the test was dragging the row forward and then backward.  Why making the star larger surfaced this issue, I am unsure...
refs #1293
=> Added a class to the required star to make it more visible

app/controllers/works_controller.rb, spec/controllers/works_controller_spec.rb, spec/requests/works_spec.rb
Also changed work_params to not default to all the params (It is just confusing).
=> Removing pre_curation_uploads from work_controller_spec

.circleci/config.yml, spec/support/system_specs.rb
This fixes the error circle ci has downloading the Browser Tools ORB
=> Updating to a newer version of the Orb

spec/system/work_upload_s3_objects_spec.rb
We are no longer looking at the pre_curation_uploads in the code, so setting them and checking them in the tests does not make sense
=> Remove pre_curation_uploads refrences from work upload test

docs/test_data_in_production.md
=> Updating the documents for loading data in production to include how to reload a single work

spec/system/data_migration/fusion_energy.xml, spec/system/data_migration/fusion_energy_form_submission_spec.rb, spec/system/data_migration/ion_orbital.xml, spec/system/data_migration/ion_orbital_form_submission_spec.rb, spec/system/data_migration/non_axisymmetric.xml, spec/system/data_migration/non_axisymmetric_form_submission_spec.rb
Also updating the DOI to be correct for non_axisymmetric
fixes #1351
=> Removing invalid DOIs so that new ones can be minted by the system

app/models/pdc_serialization/datacite.rb, spec/models/pdc_serialization/datacite_spec.rb
=> Fixes issue serializing DataCite for records without an award number

config/locales/en.yml
=> Added translation for file download privileges

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
=> Extending S3QueryService#client invocations of #get_object with #get_object_attributes for S3 Object metadata

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
=> Ensures that AWS S3 client errors are logged

app/models/work.rb, spec/controllers/works_controller_spec.rb, spec/models/work_spec.rb
=> Changing references from tombstone to deletion_marker

app/models/work.rb, spec/models/work_spec.rb
=> Adding retry to DataCite publish

spec/system/data_migration/fusion_energy.xml, spec/system/data_migration/fusion_energy_form_submission_spec.rb
We had information from @astrochun https://github.com/pulibrary/pdc_describe/issues/1351#issuecomment-1646179987
refs #1351
=> Updating DOI to the current DOI

app/controllers/users_controller.rb, app/views/users/forbidden.html.erb, spec/controllers/users_controller_spec.rb, spec/requests/users_spec.rb, spec/system/user_edit_spec.rb
=> Ensuring that only super admin. users can access the dashboards of other users

app/models/work_activity_notification.rb, spec/factories/work_activity.rb, spec/models/work_activity_notification_spec.rb, spec/system/work_comment_spec.rb
Make sure that direct message always send emails even if the user has emails disabled fixes #1382
=> Make direct messages always send emails

app/jobs/dspace_bitstream_copy_job.rb
=> Removing unused methods from DspaceBitstreamCopyJob

app/jobs/attach_file_to_work_job.rb, app/models/readme.rb, app/services/pul_dspace_aws_connector.rb, app/services/s3_query_service.rb, spec/models/readme_spec.rb, spec/services/s3_query_service_spec.rb
Files smaller than 5GB are still uploaded in one piece
fixes #1372
=> Allowing Multipart upload for files larger than 5GB

app/services/pul_dspace_connector.rb
=> Add quotes around output file name to allow for files with spaces

config/initializers/devise.rb
This was based on a request from @astrochun in slack.
=> Update devise to set the session timeout to 120 minutes

app/controllers/works_controller.rb, app/views/works/_curator_controlled_form.html.erb, app/views/works/_required_form.html.erb, spec/system/work_edit_spec.rb
=> Ensuring that the DOI for approved Works cannot be edited

app/jobs/dspace_bitstream_copy_job.rb, app/models/migration_upload_snapshot.rb, spec/jobs/dspace_file_copy_job_spec.rb, spec/models/migration_upload_snapshot_spec.rb, spec/services/pul_dspace_migrate_spec.rb, spec/system/migrate_submission_spec.rb
=> Ensuring that the S3 file object checksum is updated from AWS within DSpaceBitstreamCopyJob

app/models/group.rb, spec/models/group_spec.rb
=> Communities and subcomminities are sorted

app/views/works/_funder_table.html.erb, app/views/works/_individual_contributors_table.html.erb, app/views/works/_organizational_contributors_table.html.erb, app/views/works/_required_creators_table.html.erb
Updated the links in the tooltips to open the link in a new tab to prevent users from losing their work in progress.
Closes #1428
=> Links in tooltip open in a new tab

app/jobs/approved_file_move_job.rb, app/jobs/attach_file_to_work_job.rb, app/models/approved_upload_snapshot.rb, app/models/background_upload_snapshot.rb, app/models/upload_snapshot.rb, app/models/work.rb, app/services/s3_query_service.rb, spec/jobs/approved_file_copy_job_spec.rb, spec/services/s3_query_service_spec.rb
fixes #1417
New display.  We did not yet get any feedback, but this is better than 15 files deleted and 15 files added with no explaination.
=> Adding ApprovedUploadSnapshot so we can show the files moving from pre-curation to post-curation

app/views/welcome/index.html.erb, spec/views/welcome/index.html.erb_spec.rb
=> Display user admin/moderator badge in the home page

app/controllers/works_controller.rb, spec/controllers/works_controller_spec.rb
=> Add a flash message to explain the files are being moved after approval

architecture-decisions/0008-migration-from-dataspace.md
=> Update migration docs to reflect the two migration menu items

app/models/work_activity.rb, spec/models/work_activity_spec.rb
=> Don't mark as backdated a note added today

app/models/pdc_metadata/creator.rb, spec/models/pdc_metadata/creator_spec.rb
=> Strips spaces from names

app/services/pul_dspace_connector.rb, spec/services/pul_dspace_aws_connector_spec.rb, spec/services/pul_dspace_connector_spec.rb, spec/services/pul_dspace_migrate_spec.rb, spec/system/migrate_submission_spec.rb
=> Allowing multiple pages of dspace files

app/services/pul_dspace_migrate.rb, spec/services/pul_dspace_migrate_spec.rb, spec/system/work_edit_spec.rb
=> Updating the message for the DataSpace migration job

app/models/pdc_metadata/affiliation.rb, app/models/pdc_metadata/creator.rb, spec/services/resource_compare_service_spec.rb
=> Allowing the Affiliation changes to be displayed in provenance log

app/views/works/_orcid_link.html.erb, spec/system/work_spec.rb
=> Encode creator names properly

app/models/group.rb, spec/controllers/works_controller_spec.rb
@astrochun [noted that I didn't use the correct publisher for PPPL](https://github.com/pulibrary/pdc_describe/pull/1453#issuecomment-1688378006) in my [previous PR](https://github.com/pulibrary/pdc_describe/pull/1453), this PR fixes that.
=> Uses the correct publisher for PPPL

app/controllers/works_controller.rb, app/decorators/form_resource_decorator.rb, app/views/works/_funder_table.html.erb, app/views/works/_individual_contributors_table.html.erb, app/views/works/_organizational_contributors_table.html.erb, app/views/works/_related_objects_table.html.erb, app/views/works/_required_creators_table.html.erb, spec/system/work_create_spec.rb
Moves logic out of the works and adds a location for the PPPL specific defaults
refs #1421
=> Add a decorator for the resource form

app/controllers/works_controller.rb, app/decorators/form_resource_decorator.rb, spec/system/pppl_work_create_spec.rb
=> Adding default funder to PPPL works

app/views/works/_funder_table.html.erb, app/views/works/_organizational_contributors_table.html.erb, app/views/works/_required_creators_table.html.erb
fixes #1473
See how it turns red if you drop a character
=> Updating the ror pattern to remove the invalid character

architecture-decisions/0012-backing-up-dataspace.md
=> 1297 adr for preservation

app/decorators/form_resource_decorator.rb, spec/system/pppl_work_create_spec.rb, spec/system/work_create_spec.rb
This was missed in the previous PR
refs #1421
fixes #331
=> Adding PPPL funder award number

.circleci/config.yml, spec/helpers/application_helper_spec.rb, spec/rails_helper.rb, spec/system/work_spec.rb
Also excludes coverage analysis for the file lib/simplecov_helper.rb
=> Ensuring that the ApplicationHelper test coverage is increased

.rubocop.yml, app/models/ark.rb, architecture-decisions/0008-migration-from-dataspace.md, lib/tasks/dspace.rake
Fixes https://github.com/pulibrary/pdc_discovery/issues/426
=> Update collection arks

.circleci/config.yml
=> Upgrading the browser tool orb

Gemfile, Gemfile.lock, app/models/ark.rb
Fixes https://github.com/pulibrary/pdc_describe/issues/1479
=> Re-try ARK updates to get past intermittent failures

app/models/upload_snapshot.rb, spec/models/upload_snapshot_spec.rb
=> Allow the checksum to be nil without error

app/javascript/entrypoints/pdc/edit_table_actions.es6, spec/system/work_create_spec.rb
=> Only allow a user to add themselves once as a creator on the work edit form

.rubocop.yml, app/models/group.rb, app/services/work_update_metadata_service.rb, docs/bulk_metadata_updates.md, lib/tasks/metadata.rake, spec/factories/work.rb, spec/fixtures/rename_pppl_dept1.json, spec/services/work_update_metadata_service_spec.rb, spec/system/data_migration/fusion_energy_form_submission_spec.rb, spec/system/user_edit_spec.rb
=> PPPL Department name change from PS&T to Discovery Plasma Science

app/assets/stylesheets/components/works/_form.scss, app/controllers/works_controller.rb, app/models/work.rb, app/services/form_to_resource_service.rb, app/views/works/_curator_controlled_form.html.erb, db/migrate/20230912203022_add_embargo_date_to_works.rb, db/schema.rb, spec/requests/works_spec.rb
Advances #1491 and deprecates https://github.com/pulibrary/pdc_describe/pull/1511
=> Extending the Work model to support embargoes and implementing authorization policies

app/services/s3_query_service.rb
=> Re-raise any errors from S3QueryService.copy_file

app/models/group.rb, spec/system/data_migration/design_arrangment_form_submission_spec.rb, spec/system/user_edit_spec.rb
Co-authored-by: Carolyn Cole <carolyncole@users.noreply.github.com>
Fixes #1498
=> added Applied Materials and Sustainability Sciences as an option

README.md, config/deploy.rb
Copying the command that was in the file for sidekiq
=> Adding capistrano command for opening up the mail catcher console

app/services/file_rename_service.rb, spec/services/file_rename_service_spec.rb
=> Replace illegal characters in legacy data

app/models/work.rb, spec/models/work_spec.rb
Please see https://solr.apache.org/guide/solr/latest/indexing-guide/date-formatting-math.html with regards to the Apache Solr timestamp formatting. Advances #1491.
=> Ensuring that the JSON-serialized Works render the Solr-formatted embargo dates and hide file attachments

app/assets/stylesheets/application.scss, app/views/works/_work_activity_provenance.html.erb
=> 1519 move help text for provenance edit form out from the see more button

README.md
=> 1497 pppl training materials

spec/system/provenance_note_spec.rb
=>  add provennance note test

.circleci/config.yml, .lando.yml, README.md
Since we're upgrading to postgres 15 in production, let's match that as closely as possible in dev and test
=> Upgrade postgres

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
=> Re-raise AWS errors to make them easier to detect and track

spec/spec_helper.rb
=> Only re-run failing system specs in CI

app/controllers/works_controller.rb, app/models/work.rb, app/models/work_activity.rb, app/views/works/_work_activity_provenance.html.erb, spec/models/work_spec.rb, spec/system/provenance_note_spec.rb, spec/views/works/work_activity_provenance.html.erb_spec.rb
=> Adding change_label select to the provenance note form

app/models/work_activity.rb, spec/system/provenance_note_spec.rb
=> final changes to #1523

app/controllers/works_controller.rb, app/models/work.rb, app/views/works/_related_objects_table.html.erb, spec/controllers/works_controller_spec.rb, spec/factories/resource.rb, spec/factories/work.rb, spec/requests/works_spec.rb, spec/support/wait_for_ajax.rb, spec/system/work_create_spec.rb
=> Ensuring that errors encountered for state transitions are handled with redirect responses for Works

app/views/works/_work_activity_provenance.html.erb
=> fixed year format

app/controllers/work_downloader_controller.rb, app/controllers/works_controller.rb
Change all locations where current_user was put into a string and put the uid instead
fixes #1578
=> Show current_user uid instead of the user in memory

config/provenance_message_writers.yml, db/schema.rb
fixes #1587
Also alphabetized the list
=> Adding the curators to the provenance message writers

spec/factories/work.rb
These were part of a failed experiment
=> Remove unused work factories

app/assets/stylesheets/application.scss, app/controllers/works_controller.rb, app/helpers/application_helper.rb, app/javascript/entrypoints/pdc/copy_to_clipboard.es6, app/models/dataset_citation.rb, app/views/works/show.html.erb, config/routes.rb, spec/controllers/works_controller_spec.rb, spec/models/data_set_citation_spec.rb, spec/system/work_show_spec.rb
=> Add Citation to the work show page

README.md
fixes #1484
Co-authored-by: Favour Nwogbo <favournwogbo21@users.noreply.github.com>
=> Update README.md to include `brew install pkgconfig`

Gemfile.lock
https://github.com/sidekiq/sidekiq/blob/main/Changes.md#714
=> Updating sidekiq to remove non retry bug

architecture-decisions/0013-preservation-s3-bucket.md
=> Adding an ADR for file replication from post-curation to preservation

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, spec/rails_helper.rb, spec/spec_helper.rb
=> Add Coveralls

app/controllers/works_controller.rb, app/models/pdc_metadata/resource.rb, spec/controllers/works_controller_spec.rb, spec/system/work_spec.rb
Also capture exceptions during validation
refs #1613
=> Updated the works controller to utilize DataCiteSerialization for XML validation

app/views/users/show.html.erb, spec/system/user_show_spec.rb
=> Adding the submission counts to the dashboard

app/javascript/entrypoints/pdc/edit_required_fields.es6, app/views/works/_individual_contributors_table.html.erb, spec/system/work_edit_spec.rb, spec/system/work_spec.rb
Also makes sure the role is loaded when the edit form is returned to 
fixes #1613
=> Adding javascript to make sure contributor role is filled in

app/models/work.rb, app/views/works/show.html.erb, config/super_admins.yml, spec/system/data_migration/sowingseeds_form_submission_spec.rb, spec/system/work_upload_s3_objects_spec.rb
=> Total file size

app/models/work.rb, spec/models/work_spec.rb
Ref https://github.com/pulibrary/pdc_discovery/issues/542
=> Add created_at and updated_at to json document

app/views/welcome/how_to_submit.html.erb, spec/views/welcome/how_to_submit.html.erb_spec.rb
=> Changing response time to 5-10 days

app/models/group.rb, spec/models/group_spec.rb, spec/system/work_edit_spec.rb
=> Added PPPL subcommunities 

app/views/works/_license_text.html.erb, app/views/works/review.html.erb, spec/fixtures/files/bitstreams/license.txt, spec/system/license_spec.rb, spec/system/pppl_work_create_spec.rb, spec/system/work_create_spec.rb
=> Updating the license agreement

app/models/user.rb, app/views/works/show.html.erb, spec/models/user_spec.rb, spec/system/work_show_spec.rb
=> Showing the full name in the curator drop down select on the work show page

app/models/work.rb, app/models/work_activity.rb, spec/models/work_spec.rb
Includes the link to the work in the notification that somebody has been assigned as the curator for the work.
Closes #1536
Co-authored-by: Claudia Lee <claudiawulee@users.noreply.github.com>
=> Include link to work in curator notification

app/controllers/works_controller.rb, app/services/work_compare_service.rb, spec/models/work_activity_spec.rb, spec/models/work_spec.rb
=> Ensuring that group membership updates for Work models are properly logged within WorkActivity objects and rendered for the Work show view

app/controllers/work_downloader_controller.rb, app/controllers/works_controller.rb, app/decorators/work_decorator.rb, app/views/works/_s3_resources.html.erb, spec/routing/works_routing_spec.rb, spec/system/view_data_in_s3_spec.rb
=> Ensuring that the links for file downloads within the Work show and edit views are constructed and encoded for Rails routing

app/views/works/file_other.html.erb
=> Adds instructions for users who select more than 100mb option for a new submission

.circleci/config.yml, Gemfile, config/application.rb
=> Only require the needed groups when installing gems

app/controllers/works_controller.rb, app/views/users/show.html.erb, app/views/works/edit_wizard.html.erb, app/views/works/new_submission.html.erb, config/routes.rb, spec/controllers/works_controller_spec.rb, spec/system/pppl_work_create_spec.rb, spec/system/work_create_spec.rb, spec/system/work_spec.rb
refs #1684
Also adding documentation to the top of the file for which methods get called when.
The goal is to move the wizard to a new controller so that we can more easily update it...
=> Separating wizard new & edit and non wizard new & edit controller methods

app/controllers/works_controller.rb, app/views/works/_form.html.erb, app/views/works/_form_metadata.html.erb, app/views/works/_form_nav.html.erb, app/views/works/_form_wizard.html.erb, app/views/works/edit_wizard.html.erb, config/routes.rb, spec/controllers/works_controller_spec.rb, spec/system/work_create_spec.rb
This continues work in preparation for #1684.  Another step to moving the wizard into it's own controller
=> Separating update into wizard and non wizard methods

app/decorators/form_resource_decorator.rb, app/views/works/_curator_controlled_form.html.erb, app/views/works/_form_hidden_fields.html.erb, app/views/works/_form_metadata.html.erb, app/views/works/_required_creators_table.html.erb, app/views/works/_required_form.html.erb, app/views/works/_required_title.html.erb
Also adds doi_mutable? to the form decorator
refs #1684 
Making a smaller change because moving theses with the wizard controller  complicates that PR
=> Putting in non relative path to shared partials

app/controllers/application_controller.rb, app/controllers/works_controller.rb, app/controllers/works_wizard_controller.rb
also clean up the wizard controller a bit to remove rubocop vialation
=> Updating works (wizard and normal) controllers to share code

app/views/works_wizard/new_submission.html.erb
=> Update language and links on New Submission splash page

.circleci/config.yml
=> Run bundle install in CI

.github/workflows/pages.yml, .gitignore, Gemfile, Gemfile.lock
=> Auto-publish code docs on github

app/controllers/application_controller.rb, app/controllers/works_controller.rb, app/controllers/works_wizard_controller.rb, app/services/work_compare_service.rb, spec/controllers/works_wizard_controller_spec.rb, spec/services/work_compare_service_spec.rb
save_only returns the user to the current screen after saving instead of redirecting to the next step
Refs #1684
=> Added save_only parameter processing to Wizard Controller update methods

app/views/works_wizard/new_submission.html.erb, spec/system/authz_submitter_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/external_ids_spec.rb, spec/system/pppl_work_create_spec.rb, spec/system/work_create_spec.rb, spec/system/work_spec.rb
=> updating action buttons on wizard

app/controllers/works_wizard_controller.rb, app/services/work_metadata_service.rb, app/views/works_wizard/readme_select.html.erb, app/views/works_wizard/review.html.erb, spec/system/work_wizard_reverse_spec.rb
- testing the wizard in reverse order
- adding additional buttons to the work wizard
refs #1684
=> ensuring that the wizards buttons travers in the same order forwards and backwards

app/assets/stylesheets/application.scss, app/controllers/works_wizard_controller.rb, app/services/work_metadata_service.rb, app/views/works_wizard/_form_wizard.html.erb, app/views/works_wizard/attachment_select.html.erb, app/views/works_wizard/file_other.html.erb, app/views/works_wizard/file_upload.html.erb, app/views/works_wizard/new_submission.html.erb, app/views/works_wizard/readme_select.html.erb, app/views/works_wizard/review.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/works_wizard_controller_spec.rb, spec/system/authz_submitter_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/external_ids_spec.rb, spec/system/pppl_work_create_spec.rb, spec/system/work_create_spec.rb, spec/system/work_spec.rb, spec/system/work_wizard_reverse_spec.rb, spec/system/work_wizard_spec.rb
=> Adding Save, Next and Previous buttons to the wizard form

app/assets/stylesheets/application.scss, app/views/works_wizard/attachment_select.html.erb, app/views/works_wizard/file_other.html.erb, app/views/works_wizard/file_upload.html.erb, app/views/works_wizard/review.html.erb
=> fixing button color and order

app/controllers/application_controller.rb, app/controllers/works_controller.rb, app/controllers/works_wizard_controller.rb
Co-authored-by: Jaymee Hyppolite <jaymeeh@users.noreply.github.com>
=> Moving AASM capture from wizard controller to application controller

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
=> Enforce work count to default to 0 for new submissions

app/models/work_state_transition_notification.rb
=> Do not use accessor when reader will do

app/views/works_update_additional/_form_wizard.html.erb, app/views/works_wizard/_form_wizard.html.erb, app/views/works_wizard/new_submission.html.erb
making the cancel button route the user dashboard for the new submission and edit wizard
closes #1691
=> Refining the Cancel Button

app/assets/stylesheets/application.scss, app/views/works_wizard/attachment_select.html.erb, app/views/works_wizard/file_upload.html.erb, app/views/works_wizard/readme_select.html.erb, app/views/works_wizard/review.html.erb
=> Add cancel button to all pages in wizard

app/controllers/wizard_new_submission_controller.rb, app/controllers/works_wizard_controller.rb, app/views/wizard_new_submission/new_submission.html.erb, app/views/works_wizard/new_submission.html.erb, config/routes.rb, spec/controllers/wizard_new_submission_controller_spec.rb, spec/controllers/works_wizard_controller_spec.rb, spec/routing/works_wizard_routing_spec.rb, spec/system/work_spec.rb
=> Updating cancel on new submission wizard page to remove empty work

app/controllers/works_wizard_controller.rb, app/views/works_wizard/file_upload.html.erb, spec/controllers/works_wizard_controller_spec.rb
=> Handle file deletes through the Wizard

app/assets/stylesheets/application.scss
=> Adjust formatting for buttons in wizard

app/decorators/work_decorator.rb, app/views/works/show.html.erb, spec/system/work_spec.rb
It no longer works, so do not use it
Fixes #1755
=> Do not untilize wizard=true in the url

app/controllers/works_wizard_controller.rb, spec/controllers/works_wizard_controller_spec.rb
=> Adding reload of snapshot so readme that was uploaded displays

app/assets/stylesheets/components/_nav.scss
=> Adding a color to the non active nav-links

app/controllers/works_wizard_controller.rb, app/models/readme.rb, spec/controllers/works_wizard_controller_spec.rb, spec/models/readme_spec.rb
=> Making sure the provenance record is updated correctly for the readme step

app/views/works/_s3_resources.html.erb, app/views/works_wizard/file_upload.html.erb, spec/system/work_wizard_spec.rb
=> Prevents the user from deleting the README while on the Wizard

app/models/work.rb, spec/models/work_spec.rb, spec/system/authz_submitter_spec.rb, spec/system/view_data_in_s3_spec.rb, spec/system/work_edit_spec.rb, spec/system/work_spec.rb
=> Only allow the user to edit their work before it is awaiting approval

app/services/s3_query_service.rb, spec/services/s3_query_service_spec.rb
Remove code that substracted one from the file count since it looks like we don't need it anymore.
Closes #1769
=> Fixes file count

docs/s3_log_files.md
Documented how to download and parse the S3 log files
Related to #1785
=> Documentation: Parsing S3 Log Files 

app/views/wizard_new_submission/new_submission.html.erb
=> Removes repeated text in wizard's step 0

docs/s3_log_files.md
Document how to use lnav with our AWS S3 logs.
Part of https://github.com/pulibrary/pdc_describe/issues/1785
=> Document how to use lnav 

app/views/works_wizard/review.html.erb, spec/system/authz_super_admin_spec.rb, spec/system/external_ids_spec.rb, spec/system/pppl_work_create_spec.rb, spec/system/work_create_spec.rb, spec/system/work_wizard_spec.rb
=> Grant license notification dialogue

docs/wizard_flow.md
Shows the different controllers and how they connect together
=> Adding a mermaid diagram of the wizard flow

app/controllers/works_wizard_controller.rb, app/controllers/works_wizard_submission_complete_controller.rb, app/views/works_wizard_submission_complete/show.html.erb, config/routes.rb, docs/wizard_flow.md, spec/controllers/works_wizard_controller_spec.rb, spec/controllers/works_wizard_submission_complete_controller_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/external_ids_spec.rb, spec/system/pppl_work_create_spec.rb, spec/system/work_create_spec.rb, spec/system/work_wizard_spec.rb
=> Adding a submission completion page

config/deploy.rb, config/deploy/production_primary.rb, config/deploy/production_secondary.rb
=> Add the ability to do a rolling deploy in production

app/models/readme.rb, spec/models/readme_spec.rb
Also allow for upper and lower case
fixes #1820
=> Allow README to be any part of the filename.

README.md
You can only do read operations.  Write operations fail.  I'm guessing it is the http vs https
=> Update README.md to add additional information about the application:webapp command

docs/how_to_generate_migration_spreadsheet.md
=> Document generating the migration spreadsheet

config/environments/production.rb
Since this is a production only change, I ran it manually before making the PR and the mail went through...
=> Update production.rb to the new mail server

app/controllers/application_controller.rb, app/controllers/works_wizard_controller.rb, app/helpers/application_helper.rb, app/models/work.rb, app/services/work_validator.rb, app/views/layouts/application.html.erb, spec/controllers/works_controller_spec.rb, spec/controllers/works_wizard_controller_spec.rb, spec/requests/works_spec.rb, spec/services/work_validator_spec.rb, spec/system/migrate_submission_spec.rb, spec/system/work_approve_spec.rb
=> Ensures that one and only one README file is uploaded and that there is one or more files uploaded for any given Work

Gemfile, Gemfile.lock, config/initializers/devise.rb
=> Upgrading devise to releases 4.9 and omniauth releases 2.1

app/models/readme.rb, app/services/work_validator.rb, spec/controllers/works_controller_spec.rb, spec/controllers/works_wizard_controller_spec.rb, spec/models/work_state_spec.rb, spec/services/work_validator_spec.rb, spec/system/external_ids_spec.rb, spec/system/migrate_submission_spec.rb, spec/system/work_create_spec.rb
=> Ensuring that at least one file upload is provided for draft Works

app/controllers/welcome_controller.rb, app/views/shared/_header.html.erb, app/views/welcome/help.html.erb, config/routes.rb, spec/views/welcome/help.html.erb_spec.rb
=> Add new Need Help page

.circleci/config.yml, Gemfile, Gemfile.lock, config/database.yml, spec/rails_helper.rb, spec/spec_helper.rb
=> Restores coverage reporting for Coveralls

app/controllers/groups_controller.rb, app/controllers/users_controller.rb, app/controllers/works_controller.rb, app/controllers/works_wizard_controller.rb, spec/controllers/groups_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/controllers/works_controller_spec.rb
Now you see an error like:
fixes #1876
=> Change unprocessable entities to 200 so the load balancer does not capture them

app/assets/stylesheets/application.scss, app/views/shared/_header.html.erb, spec/system/front_page_spec.rb, spec/views/_header.html.erb_spec.rb
Resolves #1860 by updating the nav menu for both logged-in and logged-out users and adding tests.
=> Updates navigation menu in header

lib/tasks/works.rake
=> Adding a rake task to cleanup duplicate files

config/initializers/health_monitor.rb
=> Configuring sidekiq to allow for greater latency and size

lib/tasks/works.rake
Also outputing information when the checksums do not match
=> Allowing the operator to force the cleanup of double migrated files

app/assets/stylesheets/application.scss, app/views/works/_work_activity_messages.html.erb
This is how the screen looks now:
Closes #1881
=> Moved message input box to the top of the page

config/deploy/production_secondary.rb
=> Adding the third server to secondary capistrano deploy

app/models/user.rb, spec/models/user_spec.rb
=> Handle GAP accounts logging in from CAS

README.md, lib/tasks/users.rake
Automated the steps to a rake task so it is easier to run. Stole the steps from the documentation that @carolyncole  had provided in the README.
Part of #1610
=> Set PPPL user rake task

app/assets/stylesheets/application.scss, app/views/users/_form.html.erb, spec/system/user_edit_spec.rb
Show the email of the user so they (and we) can see if the system recorded the wrong email for them.
Work towards #1905
=> Adds email to list of values we display for the user

app/javascript/entrypoints/application.js, app/javascript/entrypoints/works_wizard_policy.js, app/views/works_wizard_policy/show.html.erb
=> Refactoring the Work policy wizard JavaScript functionality without jQuery and outside of the <script> element.

app/javascript/entrypoints/application.js, app/javascript/entrypoints/works_wizard_review.js, app/views/works_wizard/review.html.erb
Builds upon the work advanced with https://github.com/pulibrary/pdc_describe/pull/1907
=> Refactoring the JavaScript used to confirm the license granted for a dataset

app/controllers/works_controller.rb, app/decorators/work_decorator.rb, app/models/work.rb, app/views/works/show.html.erb, config/routes.rb, spec/models/work_spec.rb, spec/system/work_show_spec.rb
=> Implements support for providing users with the ability to revert Works awaiting approval to draft Works

spec/controllers/works_controller_spec.rb, spec/requests/works_spec.rb, spec/services/work_preservation_service_spec.rb, spec/support/s3_query_service_specs.rb
the real code always ends with a slash https://github.com/pulibrary/pdc_describe/blob/main/app/services/s3_query_service.rb#L81
fixes #1849
=> Making sure the prefix has a slash in it

app/views/welcome/index.html.erb
=> update links on PDC Describe to static page

app/jobs/dspace_file_copy_job.rb, spec/jobs/dspace_file_copy_job_spec.rb
=> Capture the ActiveRecord timeout and retry

.circleci/config.yml
Ref https://github.com/pulibrary/tigerdata-app/issues/912
=> Report code coverage via coveralls orb

config.ru, config/application.rb, config/environments/production.rb, config/environments/staging.rb
Found a solution [here](https://github.com/opf/openproject/pull/15248)
=> Allow describe subdrictory in Rails 7.2

app/models/group.rb, spec/models/group_spec.rb
=> Ensuring that ActiveModel errors result in one retry for Group#default_user

spec/rails_helper.rb
ref https://github.com/pulibrary/pdc_describe/issues/1951
=> Fixed deprecation warning for fixture_paths

lib/tasks/works.rake
=> Adding a rake task to rename files that were missed during the migration

Capfile
Shows deployments https://app.honeybadger.io/projects/99214/deploys
=> Adding honeybadger to capfile so we can see when deploys occured

s3-config/README.md, s3-config/logs-lifecycle.json, s3-config/prod-lifecycle.json, s3-config/staging-lifecycle.json
=> Adding aws s3 bucket lifecycle configuration to the repo

app/models/group.rb, db/migrate/20241021194327_deparment_community.rb, db/schema.rb, spec/models/group_spec.rb, spec/system/work_edit_spec.rb
fixes #1970
Before the deployment
After the Deployment
=> Updating communities based on feedback

lib/tasks/works.rake
=> Adding another task to keep dataspace instead of globus

architecture-decisions/0015-embargoes.md
=> Added ADR for embargoes

.circleci/config.yml
=> Updated browser tools to get CircleCI running again

app/controllers/groups_controller.rb, app/javascript/entrypoints/edit_group_utils.js, app/models/group.rb, app/views/groups/edit.html.erb, spec/models/group_spec.rb, spec/system/group_edit_spec.rb
Do not remove all permissions, but remove based on role requested
fixes #2025
=> Allow admin to remove users from groups on the Groups edit page

app/controllers/works_controller.rb, app/models/user.rb, app/views/works/index.rss.builder, config/super_admins.yml, spec/controllers/works_controller_spec.rb, spec/system/authz_super_admin_spec.rb, spec/system/rss_spec.rb
=> Only allow for Super Admin users to access /works url path

app/services/pul_redis.rb, config/initializers/health_monitor.rb
This does not remove the original check as it is just a test
We are getting these notices often https://app.honeybadger.io/projects/99214/faults/115631944
=> Adding our own custom check to see if we can stop the flood of messages on prod

app/services/pul_redis.rb, config/initializers/health_monitor.rb
Only have the things we need in the redia check, which is the key override
=> Remove the default redis and clean up our check

app/mailers/notification_mailer.rb, app/models/work_activity_notification.rb, app/models/work_state_transition_notification.rb, app/views/notification_mailer/reject_message.html.erb, app/views/notification_mailer/reject_message.text.erb, spec/mailers/notification_mailer_spec.rb, spec/models/work_activity_notification_spec.rb, spec/system/work_edit_spec.rb
Adding a delay to the work approval notifaction email 
Adding a new notificaiton email for the rejection of a work
ref #2054
=> Improve Automated Messages

app/mailers/notification_mailer.rb, app/models/work_activity_notification.rb, app/models/work_state_transition_notification.rb, app/views/notification_mailer/new_submission_message.html.erb, app/views/notification_mailer/new_submission_message.text.erb, app/views/notification_mailer/review_message.html.erb, app/views/notification_mailer/review_message.text.erb, spec/mailers/notification_mailer_spec.rb, spec/models/work_spec.rb, spec/models/work_state_spec.rb
Adding new submission and review message for curators
ref #2053
=> Improving messges for curators/moderators

package.json, yarn.lock
see https://github.com/pulibrary/pdc_discovery/commit/3fa377ebd0bc16ac2fd92d09e049fd04bd96656e
=> Upgrade vite to 6.0 for security reasons

app/models/group.rb
=> Corrected name for Lewis-Sigler Institute of Integrative Genomics

app/services/s3_query_service.rb, config/s3.yml, spec/services/s3_query_service_spec.rb
refs https://github.com/pulibrary/princeton_ansible/pull/6025
=> Adding the embargo bucket to the S3Service

app/services/pul_s3_client.rb, app/services/s3_query_service.rb, lib/tasks/works.rake, spec/services/pul_s3_client_spec.rb, spec/services/s3_query_service_spec.rb
This will allow me to utilize that logic in a separate class for moving files
refs #2044
=> Extracting the S3 Client logic from the S3QueryService

app/models/group.rb, spec/models/group_spec.rb
=> Add more communities to communities list

app/services/pul_s3_client.rb, app/services/s3_query_service.rb, app/services/work_preservation_service.rb, spec/jobs/approved_file_copy_job_spec.rb, spec/services/pul_s3_client_spec.rb, spec/services/s3_query_service_spec.rb, spec/services/work_preservation_service_spec.rb, spec/support/s3_query_service_specs.rb
It makes more sense for the upload to be ties to the bucket, not the work
=> Move file upload to the PULS3Client

app/models/embargo_upload_snapshot.rb, app/services/work_embargo_service.rb, spec/services/work_embargo_service_spec.rb
This will move the files from post curation to the embargo bucket
refs #2044
=> Add a service for moving embargo files in post-curation

app/models/embargo_release_snapshot.rb, app/services/work_embargo_release_service.rb, config/deploy/production.rb, config/deploy/production_secondary.rb, config/deploy/staging.rb, config/schedule.rb, lib/tasks/embargo.rake, spec/services/work_embargo_release_service_spec.rb
Also adds cron job to run daily
@leefaisonr I know you have yourself assigned to #2069 but I thought I would take a stab based on the work I had already done for moving the files into the embargo bucket.
=> Add a service to release a work from embargo

app/controllers/works_controller.rb, app/models/approved_upload_snapshot.rb, app/models/work.rb, app/views/works/_s3_resources.html.erb, spec/jobs/approved_file_copy_job_spec.rb
Fixes a message that we missed in PR https://github.com/pulibrary/pdc_describe/pull/2094
=> Log the correct location in the work activity for embargoed works

app/models/researcher.rb
=> Optimize Search for Creator Autocomplete List using ActiveRecord

app/controllers/works_wizard_controller.rb, spec/system/work_wizard_spec.rb
=> Fixes bug on Wizard Save

app/models/embargo_upload_snapshot.rb, app/models/work_activity.rb, spec/models/work_activity_spec.rb, spec/services/work_embargo_service_spec.rb
=> Allow the system to be identified in work activities

architecture-decisions/0017-embargoes-upgrade.md
=> Adding a new ADR for the improved embargo situation

config/environments/development.rb, config/environments/staging.rb
Fully addresses https://github.com/pulibrary/pdc_describe/issues/2135
=> Updated ROR API URL for staging and development environments

app/models/upload_snapshot.rb, app/services/s3_move_service.rb, app/services/s3_query_service.rb, spec/services/s3_move_service_spec.rb, spec/services/s3_query_service_spec.rb
=> Allow diacritics in file names
