- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- spec/rails_helper.rb
- spec/system/accessibility_spec.rb
Resolves #6 by addressing the following:
- Adding the axe-core-rspec Gem dependency for a11y analysis
- Implementing an initial test suite for assessing the WCAG 2.0 AA and Section 508 compliance of the app
- Implementing ApplicationHelper#html_tag_attributes to provide `lang` attributes for the `html` element
> Integrates a11y analysis into the RSpec test suites

- db/migrate/20220406152726_add_orcid_to_user.rb
- db/schema.rb
- spec/models/user_spec.rb
Advances #33 (but the implementation of a user page is still required for adding the ORCiD).
> Implementing the #orcid attribute for the User model

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/datasets_controller.rb
- app/controllers/demo_controller.rb
- app/models/collection.rb
- app/models/user.rb
- app/models/user_collection.rb
- app/views/datasets/_form.html.erb
- app/views/datasets/dashboard.html.erb
- app/views/datasets/edit.html.erb
- app/views/datasets/index.html.erb
- app/views/datasets/show.html.erb
- app/views/demo/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_header.html.erb
- app/views/welcome/index.html.erb
- config/routes.rb
- db/migrate/20220414155700_create_user_collections.rb
- db/schema.rb
- spec/controllers/datasets_controller_spec.rb
- spec/models/user_spec.rb
- spec/requests/welcome_spec.rb
Allows users to be designated as submitters, administrators, or none for collections. Users can only add new datasets to the collections that they are submitters (or administrators). 
Created a edit form for Datasets that allows users to change title, ark, and collection of a given dataset. The user can only selects from the collections where they are submitters (or admins). Superadmin users can view all collections.
Closes #28
A few screenshots showing the general idea
> Adds per collection user authorization

- app/models/collection.rb
- spec/models/collection_spec.rb
If no collections are defined it will define the default system collections on the spot.
Fixes #59
> Handles gracefully when no collections are pre-defined

- app/controllers/users_controller.rb
- app/models/ark.rb
- app/models/orcid.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/users/_form.html.erb
- app/views/users/dashboard.html.erb
- app/views/users/show.html.erb
- spec/controllers/users_controller_spec.rb
- spec/factories/user.rb
- spec/models/orcid_spec.rb
- spec/models/user_spec.rb
- spec/system/add_orcid_spec.rb
- spec/system/user_edit_spec.rb
Validates that users can only edit their own ORCID, but allows super admins to edit other people's ORCIDs. The functionality applies in general to "editing a user profile" not only the ORCID field (hence it also closes issue 49).
Checks that the ORCID entered is in the expected format.
Closes #62 
Closes #49
> ORCID and user edit validation

- app/controllers/datasets_controller.rb
- app/models/dataset.rb
- app/views/datasets/_form.html.erb
- spec/models/dataset_spec.rb
- spec/system/dataset_spec.rb
The ARK is now only minted once and it's read only.
Closes #65 
Closes #68
> Mint ARK only once and make it read-only

- app/models/ark.rb
- app/models/dataset.rb
- app/views/datasets/_form.html.erb
- config/environments/development.rb
- config/environments/test.rb
- spec/controllers/datasets_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/models/ark_spec.rb
- spec/models/dataset_spec.rb
- spec/system/dataset_spec.rb
- spec/system/view_data_in_s3_spec.rb
Resolves #18 and also ensures the following:
- Updates the EZID metadata for the target URL when a new ARK is minted
- Ensures that `WebMock` is enabled but does not conflict wit h test suites which request data from the EZID API endpoint
> Implementing support for ARK validation by extending the Ark Class

- app/models/collection.rb
- app/views/collections/show.html.erb
- spec/system/collection_edit_spec.rb
Always display the super administrators for a collection (and make them not-editable)
Fixes #89
> Display super administrators in Collections

- app/controllers/datasets_controller.rb
- app/models/ark.rb
- spec/models/dataset_spec.rb
Gets the save form working again (by removing the ARK validation.) Closes #121 
The ARK validation is being updated to handle test ARKs vs real ARKs in #124
> Make sure the errors saving the dataset are rendered

- app/assets/stylesheets/application.css
- app/controllers/works_controller.rb
- app/models/datacite.rb
- app/models/work.rb
- app/views/collections/show.html.erb
- app/views/works/_creators_form.html.erb
- app/views/works/_form.html.erb
- app/views/works/_titles_form.html.erb
- app/views/works/show.html.erb
- spec/controllers/works_controller_spec.rb
- spec/factories/work.rb
- spec/fixtures/files/datacite_basic.xml
- spec/models/work_spec.rb
Added the ability to delete creators and several validations (e.g. must have at least one creator, must have a publisher and a publication year)
Notice that I also updated the way creators are rendered on the page so that they are always rendered via JavaScript (instead of existing creators via Ruby and new creators via JavaScript). This way we have a single way to rendering, testing, and maintaining this code.
Closes #112
> Add button to delete creators

- Gemfile
- Gemfile.lock
- app/controllers/works_controller.rb
- app/models/pul_datacite.rb
- app/models/work.rb
- config/initializers/inflections.rb
- spec/controllers/works_controller_spec.rb
- spec/factories/work.rb
- spec/models/doi_spec.rb
- spec/models/pul_datacite_spec.rb
- spec/models/work_spec.rb
- spec/system/accessibility_spec.rb
- spec/system/work_spec.rb
We really need to get a hold of an account on [the test doi system](https://doi.datacite.org/) for testing the ability to publish DOIs, but this spike does create draft DOIs in the live system if the client is switched and environment variables are set.  I have deleted the two DOIs that I created in the live system.  Draft DOIs can be deleted, but published ones can not.
The JSON response in the test was taken directly from the gem test.
refs #108
> Adding the datacite-ruby gem and creating a test spike

- spec/models/ark_spec.rb
- spec/support/ezid_specs.rb
Added test for Ark class `update` method that was missing in PR #136.
Fixes #146
> Added test for Ark.update

- app/controllers/works_controller.rb
- app/models/pul_datacite.rb
- app/views/layouts/application.html.erb
- app/views/works/_creators_form.html.erb
- app/views/works/_edit_javascript.html.erb
- app/views/works/_form.html.erb
- spec/controllers/works_controller_spec.rb
Allows a user to change the order of the creators. Data is saved and rendered respecting the order.
Below is an animated GIF showing it in action (it's a bit slow, but it does animate)
Note the the user cannot pick the creators table header (ORCID/Given name/Family name) and drag it, but they can put a creator row on top of the header as they drag it. It looks ugly if they do, but it causes no harm. I did not find an easy way to prevent this behavior so I am submitting this PR with this possible bug, but I think it's OK.
> First pass at allowing users to reorder the creators

- app/models/work.rb
- app/services/s3_query_service.rb
- spec/models/work_spec.rb
This updates the workaround that Carolyn did on PR https://github.com/pulibrary/pdc_describe/pull/165 to use a known DOI value that skips the fetching of data from S3 https://github.com/pulibrary/pdc_describe/blob/main/app/services/s3_query_service.rb#L48 since we don't want to fetch values from S3 for this fake DOI.
> Use a known DOI to by pass the S3 service

- app/views/works/_edit_javascript.html.erb
Turns out the jQuery plug-in has a way to account for the issue by telling it not to kick-in on certain elements. In our case I told it not to kick in on textboxes or the delete icon.
Fixes #169
> Preserves the ability to click on the edit textboxes

- app/models/orcid.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/works/_edit_javascript.html.erb
- spec/models/orcid_spec.rb
Several minor tweaks including allowing spaces at the end of the ORCID (this is useful when users copy and paste an ORCID) and removing these extra spaces before saving to the database.
I am also using a slightly different regex that allows an `X` as the last "digit" since this is apparently OK.
Notice that we do the ORCID validation both in JavaScript and in Ruby and therefore the regex is in two places. This is OK and no big deal.
We also have the regex twice in JavaScript and at some *future PR* I would like to change that so that the JavaScript `isOrcid()` function is defined only once.
Fixes https://github.com/pulibrary/pdc_describe/issues/150
> Tuned the ORCID validation

- app/models/work.rb
- spec/models/work_spec.rb
Added the ORCID format validation for each of the creators of a dataset. 
It is OK for a creator to not have an ORCID, but if the creator has an ORCID it must be in the correct format e.f. 0000-0000-0000-0000-0000.
Closes #151
> Added ORCID format validation for the dataset creators

- app/models/pul_datacite.rb
- app/views/works/show.html.erb
- spec/fixtures/files/datacite_basic.xml
- spec/models/pul_datacite_spec.rb
In a previous PR I added the description to the Edit form. This PR displays it on the Show page and adds it to the DataCite XML rendering as well.
> Displays description in show page and DataCite XML

- README.md
- app/models/work.rb
- app/services/s3_query_service.rb
- spec/models/work_spec.rb
- spec/support/datacite_specs.rb
Updated the code to use a variable DOI prefix based on the environment. 
Updated error handling in DOI generation and when fetching S3 files associated with a DOI that has no files in S3 yet. Also added special condition to allow the system to work in development without having to have the DataCite credentials.
> Updating DOI code to utilize prefix environment variables

- .rubocop.yml
- app/models/work.rb
- spec/models/work_spec.rb
Update the dashboard to include works where the user is mentioned (even if they don't own the dataset). 
This is to handle cases where a user tags a user, say `@userA`, on a dataset that they typically does not have access to (e.g. it's the PPPL collection). With this changes the dataset will still show under `@userA's` dashboard and with the proper badge indicating that there are unread notifications.
Closes #223 
Below is an example on how this looks in practice. Notice that the dashboard for Bess has a dataset with a badge with one pending notification because Bess was mentioned in a comment for this dataset.
> Include works where the user is mentioned 

- app/assets/stylesheets/application.scss
- app/controllers/works_controller.rb
- app/views/users/show.html.erb
- app/views/works/_edit_javascript.html.erb
- app/views/works/_form_hidden_fields.html.erb
- app/views/works/_required_creators_table.html.erb
- app/views/works/_required_form.html.erb
- app/views/works/_required_title.html.erb
- app/views/works/new_submission.html.erb
- config/routes.rb
- spec/controllers/works_controller_spec.rb
- spec/system/work_spec.rb
Updated the Step 0 in the wizard to submit a new dataset to allow/force the user to indicate the *Title* and at least one *Creator* as requested on #199. This new workflow has the advantage that we will have at least two basic bits of information before we mint a DOI.
The following screenshots show the general workflow.
Closes #199
> Submit new dataset step 0

- Gemfile
- Gemfile.lock
- spec/models/doi_spec.rb
Updated the gem to allow for xml format, which is why we are pointing at main.
Draft PR on gem, which allowed for the above to be published via xml: https://github.com/sul-dlss/datacite-ruby/pull/18
Tested by creating a new item via `rspec spec/models/doi_spec.rb:68` and then running `rspec spec/models/doi_spec.rb:142` with the new id.  (Connected to the real server)
> Adding sending of XML to datacite

- app/models/work.rb
This makes reading the code easier and maintaining easier, becuase there is a clear indication that these methods are only utilized internally by the class and not by other classes
> Moving private helper methods to the private tag

- app/models/work.rb
- spec/models/work_spec.rb
I believe this is easier to read, but I would be happy to hear otherwise.
It should be more performant with al the calculations occurring in one database call.
> Updating new notification count to be one sql query

- app/models/work.rb
- spec/models/work_spec.rb
The live code always passes one.  We should be explicit in our tests that we are not passing one.
Also when I commented out the defaulting of the object all the tests still passed.
This is an effor to understand the code in the create_dataset routine.
> Making datacite/metdata required to create_dataset

- app/models/work.rb
- spec/controllers/works_controller_spec.rb
After the event the work is is the correct state, but after transition the model has not yet been updated
fixes #295
> Updating assm callback to after_event instead of after_transition

- app/controllers/works_controller.rb
- app/models/pul_datacite.rb
- app/models/work.rb
- db/migrate/20220816121418_work_remove_title.rb
- db/schema.rb
- spec/controllers/works_controller_spec.rb
- spec/factories/resource.rb
- spec/factories/work.rb
- spec/models/work_spec.rb
- spec/system/accessibility_spec.rb
- spec/system/work_spec.rb
- spec/views/works/file_upload.html.erb_spec.rb
It already lives in the json metadata.  Having it in two places is causing confusion.
fixes #274
> Removing the title field from the work object

- docs/work_states.md
It is not safe to go directly between withdrawn and awaiting approval.  It is possible for a withdrawn item to have come from a draft state, so we should go back to draft.
> Should not directly between withdrawn and awaiting approval

- app/controllers/works_controller.rb
- app/models/work.rb
- app/views/works/_transition_errors.html.erb
- app/views/works/show.html.erb
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
Changed ready_for_review transition to complete_submission so it sounds more like an action and not a state
Also changing to utilize AASM bang methods.  Instead of an explicit save! in logging, changing to use the bang methods like approve! which force a save.
fixes #207
> Add error handling for AASM

- app/controllers/works_controller.rb
- app/models/pdc_metadata/resource.rb
- app/models/work.rb
- config/initializers/inflections.rb
- spec/factories/resource.rb
- spec/models/pdc_metadata/resource_spec.rb
- spec/models/work_spec.rb
- spec/system/accessibility_spec.rb
- spec/system/work_spec.rb
This is just renaming the class and moving it to a directory.  To complete #275 more needs to be done, but I wanted to make the PRs easier to review
This was a basic search and replace of PULDatacite to PDCMetdata.
> Renaming PULDatacite to PDCMetadata

- lib/tasks/works.rake
Stubs a DOI value on records without one so they can be fixed with the rake task `transfer_doi_fix` that was added as part of PR https://github.com/pulibrary/pdc_describe/pull/316
DOI is always available in new records, but looks like at one point we had records without one.
> Fixes DOI value in old records

- app/models/work.rb
- db/migrate/20220823094818_work_remove_doi_ark.rb
- db/schema.rb
- spec/factories/work.rb
- spec/models/work_spec.rb
- spec/system/accessibility_spec.rb
Drop the work.doi and work.ark database columns since now we store the data as part of the JSON `resource` field. Aliased their getters in the work model (but not the assignments) and updated the tests
> Drop the work.doi and work.ark database columns

- app/models/pdc_metadata/affiliation.rb
- app/models/pdc_metadata/creator.rb
- app/models/pdc_metadata/name_identifier.rb
- app/models/pdc_metadata/resource.rb
- app/models/pdc_metadata/title.rb
- spec/models/pdc_metadata/resource_spec.rb
Also removing rubocop violations
refs #275
> Breaking out PDCMetadata classes into thier own files

- app/controllers/works_controller.rb
- app/models/pdc_metadata/creator.rb
- app/models/pdc_metadata/name_identifier.rb
- app/models/pdc_metadata/resource.rb
- spec/controllers/works_controller_spec.rb
- spec/fixtures/files/datacite_basic.xml
- spec/models/pdc_metadata/resource_spec.rb
- spec/system/work_spec.rb
`PDCMetadata::Resource.to_xml` had a custom XML serialization that we added initially to show how we can output Datacite XML out of our data. This PR drops the custom implementation in favor of the one that we now provide in `PDCSerialization::Datacite.to_xml`. 
Closes #328
> Use our new XML serialization

- app/models/collection.rb
- config/collection_defaults.yml
- lib/tasks/users.rake
- spec/models/collection_spec.rb
- spec/models/user_spec.rb
- spec/models/work_spec.rb
- spec/services/s3_query_service_spec.rb
Remove code references to non-existing collections. Added rake task to clean up database records as well.
```
bundle exec rake users:collection_cleanup
bundle exec rake users:collection_cleanup[true]
```
Closes #335
> Collections clean up

- app/assets/stylesheets/application.scss
- app/views/users/_form.html.erb
- app/views/works/_additional_form.html.erb
- app/views/works/_edit_javascript.html.erb
- spec/system/work_spec.rb
Added a hint to the data entry to indicate the expected format of the ARK (if entered). 
I also added a convenience method to drop the "http://arks.princeton.edu/" part of an ARK if a user enters it. This should help when we migrate data from DataSpace in which the full ARK URL (e.g. "http://arks.princeton.edu/ark:/88435/dsp01hx11xj13h") is available to the user at the top but we only care about the core ARK identifier (e.g. "ark:/88435/dsp01hx11xj13h")
Closes #327
> ARK tooltip on data entry

- app/models/work.rb
- spec/system/work_spec.rb
This is one way to address the issue with `work.reload` not reloading the `work.resource`.
I am not too happy with having to overload ActiveRecord's `reload` method but this was the only way I could get it to work. Left a big comment about it on the code. 
Fixes #365
> Force the work.resource to be reloaded when work.reload is called

- app/models/user.rb
- spec/factories/user.rb
- spec/models/user_spec.rb
- spec/system/authz_super_admin_spec.rb
Needed to adjust the roles a bit to allow the access to be right
fixes #306 
This change is utilizing the rolify add role without an object to allow access to any instance of that object.  `user.add_role :collection_admin` vs `user.add_role :collection_admin, collection`
> Adding tests to verify a super admin can access all works and collections

- app/models/user.rb
- lib/tasks/users.rake
- spec/models/user_spec.rb
Even if another role has already been assigned.  Each user should get access to thier default collection
Also removes reference to setup_user_default_collections as it no longer exists.  Utilizing assign_default_role instead
> Allow access to default collection

- app/models/collection.rb
- app/models/user.rb
- spec/controllers/collections_controller_spec.rb
- spec/system/authz_admin_spec.rb
- spec/system/collection_edit_spec.rb
When a user is first added to the system and they are being added as a submitter to thier default collection and error is not needed.
Only error to say the user has already been added if someone tries to add them again
fixes #372
> Allow a user to be added to their default collection

- app/javascript/packs/application.js
I found that this error, also, needed to be resolved for the `staging` environment.
> Ensures that `window.rails` is not already defined before initializing `Rails.start()` for rails-ujs

- app/controllers/works_controller.rb
- app/services/work_uploads_edit_service.rb
- config/environments/test.rb
- spec/controllers/works_controller_spec.rb
- spec/factories/work.rb
- spec/models/work_spec.rb
- spec/services/work_upload_edit_service_spec.rb
- spec/system/work_spec.rb
Also makes sure the files still exists both before and after an edit. 
Also makes sure the files still display both before and after an update error.
fixes #376 and fixes #400
> Allow files to be displayed after edit

- app/models/work.rb
- config/routes.rb
- spec/controllers/works_controller_spec.rb
- spec/routing/works_routing_spec.rb
These errors were discovered after testing the latest deployment of PDC Describe.
> Ensures that ARK and DOI resolution routing handles non-alphanumeric characters

- spec/controllers/works_controller_spec.rb
- spec/models/doi_spec.rb
- spec/models/work_spec.rb
- spec/services/s3_query_service_spec.rb
- spec/system/authz_admin_spec.rb
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/authz_unauthenticated_spec.rb
- spec/system/external_ids_spec.rb
- spec/system/form_submission_spec.rb
- spec/system/rss_spec.rb
- spec/system/work_spec.rb
- spec/views/works/file_upload.html.erb_spec.rb
DOIs are minted and ARKs are NOT.
Removing mocking for ezid in locations where it was not needed.  The code that needed the mocking was removed in the commit aa9c96ee97e2c3d8e205e1bd556a9d86c35fcef2
refs #17
> Adding Tests for minting the correct ids

- app/controllers/works_controller.rb
- app/models/work.rb
- spec/controllers/works_controller_spec.rb
It was confirmed that users should not be able to delete S3 Objects once they have been curated (please see: https://pulibrary.slack.com/archives/C02PHG9MGU8/p1663955197008019?thread_ts=1663952066.026279&cid=C02PHG9MGU8)
> Ensures that clients cannot delete post-curation S3 Objects

- app/assets/stylesheets/application.scss
- app/views/works/_form.html.erb
- app/views/works/_form_errors.html.erb
Moved the error messages to be displayed outside the tabs (see screenshot below) so that users can see them regardless of which tab they are on. This only addresses part of #426, but it moves us in the right direction. I'll submit a separate PR to address the remaining work to close #426 since that might require more thought.
> Display of error messages when saving

- config/initializers/ezid_client.rb
The culprit on the slow validation of the ARK is that the gem that we are using does an automatic retry when there is an error with the id provided. By default the gem waits 15 seconds in between retries and it retries twice. This means that if the user provides an invalid ARK the validation takes between 33-35 seconds. Of those, 30 seconds are due to the retry logic.
This is the retry logic on the gem: https://github.com/duke-libraries/ezid-client/blob/dfcf7f49995560ed48df407560c4fe3fb6dbfa7b/lib/ezid/requests/request.rb#L49-L64
This PR changes the default retry value to `1` so that retries happen (almost) immediately and a user waits between 3-5 seconds rather than 33-35 seconds.
This is the code on the gem that shows how the retry value is initialized: …
> Reduces the default retry_interval

- app/models/work.rb
- spec/factories/work.rb
- spec/models/work_spec.rb
- spec/system/view_data_in_s3_spec.rb
- spec/system/work_upload_s3_objects_spec.rb
Let's utilize the key instead of the file name.  This stops an infinite loop from occurring in tests when we trigger the validation and for S3 files to not get added repeatedly when s3 is queried. See https://pdc-describe-staging.princeton.edu/describe/works/75 for an example of a work where the files got added each time the work was saved
ActiveStorage::File to_s changes the slashes to underscores, so the names were not matching and the
> S3 key already contains the DOI

- app/controllers/works_controller.rb
- app/services/form_to_resource_service.rb
- app/views/works/_curator_controlled_display.html.erb
- spec/controllers/works_controller_spec.rb
Only allow collection admins the ability to update curator controlled metadata (currently doi and ark) Moving code from controller into a service
fixes #421
> Updating the controller to check before updating metadata

- spec/models/s3_file_spec.rb
```
An expectation of `:bucket_name` was set on `nil`. To allow expectations on `nil`
```
> Removing nil deprecation warning

- app/controllers/works_controller.rb
- app/services/work_uploads_edit_service.rb
- config/environments/development.rb
- spec/controllers/works_controller_spec.rb
- spec/services/work_upload_edit_service_spec.rb
- spec/system/work_edit_spec.rb
We no longer rely on ActiveStorage to do the Right thing, by setting the attribute pre_curation_uploads. 
Instead we explicitly call purge on items that are deleted.  ActiveStorage will utilize a purge_later which introduces a timing issue when deleting items and then reloading from S3 for the show page, immediately after the deletes.
fixes #394
> Explicitly deleting files as they change

- app/controllers/works_controller.rb
- app/models/work.rb
- config/locales/en.yml
- spec/controllers/works_controller_spec.rb
- spec/factories/work.rb
Stop the user from editing the work at the controller level after the work has been approved
refs #255
This is a first step.  We would still need to remove the edit button from the page, and protect the update action.  I think those can be done as separate PRs to keep them smaller.
> Do not allow edit by submitter after approved

- app/views/works/show.html.erb
- spec/system/view_data_in_s3_spec.rb
Only curators and super admins should have edit capabilities on approved works. There is a pending test, because there is a bug on the edit screen for approved works (#505).
refs #255
> Removing Edit button from show of approved work

- app/controllers/works_controller.rb
- spec/controllers/works_controller_spec.rb
Also do not allow updates by users who do not have access to this work.  This was a bug I discovered while working on the ticket. 
Additionally refactor the update routine to make rubocop happy
fixes #255
> Only allow user to update non approved work

- app/models/pdc_metadata/resource.rb
- app/services/form_to_resource_service.rb
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
- spec/system/curator_controlled_metadata_spec.rb
Allow the resource type to change when the entire resource is assigned. fixes #502
The resource type and resource type general were not connected back through to the model at any point in the edit cycle.
> Allow resource type to change on assignment

- .rubocop.yml
- app/models/work.rb
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
- spec/support/s3_query_service_specs.rb
- spec/support/work_s3_requests_specs.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/migrate_submission_spec.rb
- spec/system/rss_spec.rb
- spec/system/view_data_in_s3_spec.rb
Advances #256 by addressing the following:
- Files no longer exist in the pre-curation bucket
- Files should exist in the post-curation bucket in a directory that is the dataset DOI
- The directory in the pre-curation bucket should be removed
- An error is raised if the post-curation bucket already has a directory for the DOI
- Make sure it exists in the new location, before deleting it in the old location
> Improvements for the transfer of pre-curation uploads to the post-curation S3 Bucket for Works

- app/controllers/works_controller.rb
- app/models/pdc_metadata/creator.rb
- app/models/work.rb
- app/models/work_activity.rb
- app/services/form_to_resource_service.rb
- app/services/resource_compare.rb
- app/services/resource_compare_service.rb
- app/views/works/_curator_controlled_form.html.erb
- app/views/works/show.html.erb
- spec/controllers/works_controller_spec.rb
- spec/services/resource_compare_service_spec.rb
Keeps tracks of changes to the metadata (provenance log) in works. 
Handles the Provenance Log part of #198 for **metadata**. See issue #517 for file provenance log.
Closes #198
> Log changes

- app/views/works/_edit_javascript.html.erb
- app/views/works/show.html.erb
- spec/system/work_edit_spec.rb
Tiny enhancement to the change log display
> Allow user to toggle display of change history

- README.md
- Fix #526
Maybe the 3.v. step shouldn't be needed? Not sure if there's a better way for it to work out of the box.
I also wonder if down the road it would be worth pulling CI and dev environment from the same place... but probably not worth worrying about until we hit a problem.
> Reference asdf in install instruction

- config/locales/devise.en.yml
- spec/controllers/omniauth_callbacks_controller_spec.rb
- Fix #542
I'm not sure how to produce a failed login, but the flash message for a successful login seems right now.
> fix repeated "from"

- app/models/work.rb
- config/s3.yml
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
- spec/support/work_s3_requests_specs.rb
- spec/system/rss_spec.rb
This makes sure that it only is triggered once when the work is approved, not every time the work is saved after an approval.
Additionally changed the post-curation bucket in testing to have a different name from the pre-curation bucket.  This made understanding the mocking easier for me.  It turns out when we move the logic to publish files into the approve step, then the S3QueryService built into the work can get instantiated when the item is not approved.  This points it at pre-curation instead of post-curation resulting in some strange testing errors.
I should also point out that we were approving works that did not include files, which should not have been possible.  This change causes an error during the approve when no files are part of the work.  That caused me to need to add …
> Move publish step to approve

- app/controllers/works_controller.rb
- app/models/work.rb
- app/views/works/_form.html.erb
- spec/system/view_data_in_s3_spec.rb
Only show the ability to edit the uploads before the Work is approved, since after it has been approved we drive everything off of S3 
Also changed test for edit of an approved work to administered by so that as an administrator I could edit my own work.
fixes #505
> Updating the edit form to only show upload edits before approval

- app/controllers/works_controller.rb
- app/models/work.rb
- app/models/work_activity.rb
- app/services/work_uploads_edit_service.rb
- app/views/works/show.html.erb
- config/storage.yml
- spec/services/work_upload_edit_service_spec.rb
- spec/system/work_edit_spec.rb
Logs file changes (add/delete) when done via the Work Edit page.
Works towards #517
The bulk of the changes in this PR are on the `WorkUploadsEditService` class. I made the methods in this class instance methods (rather than class methods) so that we can keep track of the changes. Notice the new calls to `track_change(...)` and `work.log_file_changes(@changes, @current_user)`. The rest of the logic stayed the same.
> Log file changes

- spec/services/s3_query_service_spec.rb
refs #309
The collection was not utilized, otherwise the test would have failed.
> Removing the library_resource collection

- app/models/work.rb
- spec/models/work_spec.rb
- Fix: #563
- Blocked by: #571
The tests currently set an invalid state, so those tests will error out in this branch. I made an attempt to fix that in #571... but I'm not super confident about that work, so I didn't base this branch on that one. Where ever the fix comes from, that PR or a different one, once it's merged to main, merge main to this branch, and it should be green.
Overriding the setter and catching the error at the earliest possible point feels good, but there may be other approaches. I looked at `no_direct_assignment`, but that causes tons of FactoryBot errors.
> Validate work state

- app/services/work_uploads_edit_service.rb
- app/views/works/_uploads_form.html.erb
- spec/controllers/works_controller_spec.rb
- spec/services/work_upload_edit_service_spec.rb
- spec/system/work_edit_spec.rb
This will allow the replacement to be more accurate and replace the expected upload.
fixes #557
> Updating replacement key to be upload key

- README.md
It sounds like different folks are doing different things. Here's one possibility that's just an addition to the docs, but down the road I think it would be even cleaner to do check in a script something like this:
```
#!/usr/bin/env bash
set -o errexit
export AWS_S3_PRE_CURATE_BUCKET=pdc-describe-staging-precuration
export AWS_S3_POST_CURATE_BUCKET=pdc-describe-staging-postcuration
$(lpass show 'Shared-ITIMS-Passwords/princeton_ansible/RDSS Globus AWS' --notes)
bundle exec rails s -p 3000
```
This is something that I got stuck on for a little bit -- if there's a different way that it should be done, or it's already documented elsewhere, or there's some standard practice, great!
> Document how to set envvars

- app/views/works/_additional_form.html.erb
- app/views/works/_curator_controlled_display.html.erb
- app/views/works/_curator_controlled_form.html.erb
- spec/system/attention_form_submission_spec.rb
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/bitklavier_form_submission_spec.rb
- spec/system/cklibrary_form_submission_spec.rb
- spec/system/cytoskeletal_form_submission_spec.rb
- spec/system/femtosecond_form_submission_spec.rb
- spec/system/form_submission_spec.rb
- spec/system/migrate_submission_spec.rb
- spec/system/work_edit_spec.rb
> Moving the Work form fields `Publisher`, `Publication Year`, and `Collection` to the `Curator Controlled` section

- app/models/work.rb
Instead of writing our own getter methods delegate methods to the resource in the work
> Utilize Delegate from Work to Resource

- spec/system/data_migration/bitklavier_form_submission_spec.rb
Validating bitklavier xml against local datacite schema.  ticket #603
> Validating bitklavier datacite schema

- spec/system/data_migration/bitklavierimage_form_submission_spec.rb
Validating bitklavierimage xml against local datacite schema. ticket #603
> validate bitklavierimage xml datacite schema

- app/models/pdc_metadata/rights.rb
- spec/system/work_spec.rb
- Fix #624
- Since we only have two of these, thought it made sense to list them above the CC licenses, so they don't get lost.
- I think GNU should be all-caps?
- Not sure about the best URLs to include here: The GNU one is "official"... but maybe you'd prefer something like https://opensource.org/licenses/gpl-license?
(PR targets my bundle branch... if we don't end up accepting that, I'll add a revert for the bundle config at the tip.)
> Add OS licenses

- app/controllers/works_controller.rb
- app/models/work.rb
- app/views/works/show.html.erb
- spec/requests/works_spec.rb
- spec/support/work_s3_requests_specs.rb
Resolves #633 and modifies `spec/support/work_s3_requests_specs.rb` in order to stub HTTP requests for cases where Works have no S3 file attachment objects.
> Ensures that invalid or `nil` Collections associated with Works raise errors

- spec/system/data_migration/femtosecond_form_submission_spec.rb
Validating Femtosecond xml against local datacite schema. ticket #603
> Validate femtosecond xml datacite schema

- app/models/pdc_metadata/related_object.rb
- app/models/pdc_metadata/title.rb
- app/models/work.rb
- app/services/resource_compare_service.rb
- spec/models/work_spec.rb
- Fix #627 
- Clean up copy and pasted code while I'm here.
- Make title comparison logic consistent with other objects.
- Base of this PR is my PR to change gem install location. If this is good, but that isn't, I'll add another commit on the tip of this branch to revert those bits.
Notes:
- Users were confused by `delete` + `add` when they expected just `change`; That's in the same neighborhood, but I don't see an issue for it. Just filed: https://github.com/pulibrary/pdc_describe/issues/645
- (More testing would be good but don't want to invest too much in it now if the machinery is going to change.)
- If this much is accepted, I would like to follow up with a quick refactor of the other compare methods for consistency.
> related objects in prov history

- app/views/works/show.html.erb
- Fix #622 
Tried to suggest a header hierarchy, without making the font larger.
This could be done differently, but let's try not to bikeshed this.
This  would be a little tidier in scss, but it looks like the pattern is for CSS to live close to the HTML it modifies, for the top-level ERBs, and I'm happy to continue that pattern.
> add css for headers in comments

- app/views/works/show.html.erb
- Fix #617
Before:
> <img width="863" alt="Screen Shot 2022-12-05 at 1 03 29 PM" src="https://user-images.githubusercontent.com/730388/205716906-89576c8a-b861-4c8f-bd69-92aaded8a782.png">
After:
> <img width="523" alt="Screen Shot 2022-12-05 at 1 50 38 PM" src="https://user-images.githubusercontent.com/730388/205718640-e04d28ca-c053-4d7e-8127-670a000e43b5.png">
Along with the [`pre` tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre), there are [several CSS options](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) for controlling how HTML handles whitespace rendering, but without adding a lot of complexity we're not going to be able to treat line-wrapping newlines differently from others.
(I also think we may want to style the labels of fields differently from …
> preserve whitespace in description

- app/services/resource_compare_service.rb
Refactoring for consistency with #668, with no change in behavior: Instead of having a compare method for each field, make generic methods which take the field to modify as an argument.
> Refactor: Same idiom as compare_objects

- app/views/works/_required_form.html.erb
- Fix #660
(The original issue mentions that the descriptive text should be normal weight... but in this case the title isn't actually bold. I've filed #673 for consistency here.)
I don't think this is exactly the picture @hhkitsune had in mind, but it lets us present the information without being too distracting to users once they are familiar with the software. Feedback welcome!
Collapsed:
Expanded:
> Use `<details>` to provide more details in fold down

- app/views/works/new_submission.html.erb
- Fix #655
This adds:
- "By clicking on the "Create New" button, ..."
- "You can find more documentation on the PRDS Data Repository Help Page."
> Add clarification to "New Submission" text

- app/models/work_activity.rb
- docs/how_to_delete_a_work.md
- spec/models/work_activity_spec.rb
This allows a user to run `work_activity.destroy` and have the dependent WorkActivityNotifications also destroyed.
Without this, you need to run  `WorkActivityNotification.where(work_activity_id: work_activity.id).each(&:destroy)` before running the `work_activity.destroy`
Otherwise you will get:
```
ActiveRecord::InvalidForeignKey:
PG::ForeignKeyViolation: ERROR:  update or delete on table "work_activities" violates foreign key constraint "fk_rails_2a0cd9ebed" on table "work_activity_notifications"
DETAIL:  Key (id)=(3) is still referenced from table "work_activity_notifications".
```
> Connect WorkActivity to WorkActivityNotifications so we have a cleaner deletion process

- app/views/works/_required_title.html.erb
- Fix #658
Removing the placeholder not explicitly requested, but since the text is much the same, and the detail fold-down seems to be preferred, thought it would be ok to delete.
> Remove Title placeholder and add details folddown

- app/models/work.rb
- app/services/s3_query_service.rb
- spec/models/work_spec.rb
- spec/services/s3_query_service_spec.rb
- spec/support/work_s3_requests_specs.rb
Changed code to copy of files from pre-curation to post-curation S3 buckets to use Amazon's own copy method so that files are copied between S3 buckets rather than require a server download and re-upload.
Closes #538
> Server-side publish files to post-curation buckets

- app/controllers/application_controller.rb
- Seems to fix #662: I can now edit a work. [Rails docs](https://edgeapi.rubyonrails.org/classes/ActiveStorage/SetCurrent.html).
- Leaving #682 open: The configuration process confuses me, [particularly in development.rb](https://github.com/pulibrary/pdc_describe/pull/301/files?diff=unified&w=1#diff-d3c4b3f41072daa416f1920511e9b2e26caea8c5cec0a14cb9508589a4dafa47):
```diff
-  config.active_storage.service = :local
+  config.active_storage.service = :amazon
```
> Fix URI bug when editting a work in a local development environment

- app/models/work.rb
- docs/how_to_delete_a_work.md
- spec/models/work_spec.rb
Allows the deletion to occur automatically when a work is deleted.
Refs #684
> Making UserWork explicitly related to Work so it is easier to delete a work

- app/views/works/_uploads.html.erb
- app/views/works/uploads/_post_curation_s3_resources.html.erb
- app/views/works/uploads/_pre_curation_s3_resources.html.erb
- config/locales/en.yml
- Prep-work for #657
Eliminate differences in the code that don't actually matter so we can isolate the differences that do matter. With these changes, the differences in the ERB are reduced to:
```diff
diff app/views/works/uploads/_{pre,post}_curation_s3_resources.html.erb
20c20
<                 <% @work.pre_curation_uploads.sort_by(&:filename).each_with_index do |file, ix| %>
---
>                 <% @work.post_curation_uploads.sort_by(&:filename).each_with_index do |file, ix| %>
25c25
<                       <a href="<%= rails_blob_path(file, disposition: "attachment") %>" class="documents-file-link" target="_blank" title="<%= file.filename %>"><%= pre_curation_uploads_file_name(file: file) %></a>
---
>                       <a href="<%= file.globus_url %>" class="documents-file-link" …
```
> Where {pre,post}_curation_uploads strings are the same, consolidate

- app/assets/stylesheets/application.scss
- Fix #694
- Replace triangle on left with question mark on right, in a round-rect
- Light grey background when help is shown, so the button itself toggles
- Help text is smaller than label
- Bold the field label
Not sure if there's a lower-level file that this CSS would better belong in?
> Field help: Replace triangle with question mark

- app/views/works/_work_activity.html.erb
- app/views/works/_work_activity_history.html.erb
- app/views/works/show.html.erb
- spec/system/work_edit_spec.rb
- Fix #677
- Change "Activity History" to "Change History" for clarity
- Remove view toggle, since they are separate sections.
- Add a "No comments" / "No changes" message if needed, rather than hiding the entire section. (With more sections, I think conditional display can get more confusing.)
> Separate comments from other changes

- config/storage.yml
- lib/tasks/works.rake
fixes #664
fixes #684
This allows us the delete works that we create, but not works others create.
> Adding a rake task to clean out works for a user so we can clean out old tests data from staging & production

- app/assets/stylesheets/application.scss
This matches the CSS on the sidebar buttons (with the exception of the padding around the text.)
It removes special styling for the button in the open state.
- Fix #710
> Apply a blue background to help button

- app/assets/config/manifest.js
- app/assets/javascripts/show_work_utils.js
- app/assets/stylesheets/application.scss
- app/views/works/show.html.erb
- spec/system/work_show_spec.rb
Added a button to the DOI display to copy the DOI URL to the clipboard (just like we do in PDC Discovery). 
This is slightly different than what was asked on the original ticket (#696) but I discussed it with @hhkitsune and we thought mimicking PDC Discovery was a good approach.
Closes #696
> Copy button to copy DOI's URL to the clipboard

- architecture-decisions/0003-S3bucket.md
refs #499
We no longer want to allow public read/write to the globus pre-curation area.  The users will either need to upload via the application, or have a Globus account that the Curators will transfer to pre-curation from.
We need to make sure the curators have access to the S3 bucket.
> Updating the S3 Buckets ADR to indicate that we removed public access to pre-curation

- app/views/works/_required_form.html.erb
- Fix #697
Currently there are two slightly different messages depending on whether you're in the wizard or not:
```diff
... This unique identifier will become searchable at the completion of this process.
... This unique identifier will become fully minted and searchable at the completion of this process.
```
My assumption is that this was not intentional, and so to make the messaging consistent, I've moved the conditional inside, so it only wraps the DOI.
> Refine the draft-DOI message

- app/services/form_to_resource_service.rb
- spec/system/work_spec.rb
The code was defaulting the `resource_type_general` to `:DATASET` correctly but we were losing that value when coming through the New Submission process (which renders a form without this value). 
This PR makes sure we preserve the value already on `resource_type_general` when no new value comes in the form, we already were doing this for `resource_type`.
Closes #699
> Fixes issue with default value being lost for resource_type_general

- app/models/user.rb
- app/views/collections/edit.html.erb
- app/views/shared/_user_actions.html.erb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- spec/system/authz_admin_spec.rb
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/collection_edit_spec.rb
Changed the word curator to moderator in places where it represents a user's ability to moderate a collection and kept curator in places where it represents a user's ability to curate a particular work.
Closes #214
> Use moderator instead of curator

- README.md
```
% asdf plugin add node
plugin node not found in repository
% asdf install
nodejs plugin is not installed
% asdf plugin add nodejs
```
Not sure whether it was a typo originally, or if something has changed upstream.
> In README install instructions, change "node" to "nodejs"

- app/models/pdc_metadata/resource.rb
- Set all the simple fields first
- For the complex cases, establish a consistent parameter order, and make the method names verb-y
- Establish consistent behavior: all the methods modify the resource in place
No change in behavior.
> Reorder and rename resource methods for readability

- spec/models/work_spec.rb
Needed to touch this in the process of making funders multi-valued, and thought it could be more readable. This PR only changes the formatting. Surprised that there were no rubocop warnings locally.
> Use a multi-line JSON string in spec for readability

- app/services/form_to_resource_service.rb
- At the top level, in `convert`, group all the simple field setters, and group all the calls to `process` methods, and reorder the calls and definitions to be consistent.
- If `resource` is modified in place, we don't need to return and reassign it: Make the methods simple and consistent.
- Create consistent paired `process_fields`/`new_field` methods.
- Use `filter_map` to drop the empty rows.
(I'll be adding to this file for #759, and I wanted to establish a pattern I can follow.)
> Cleanup form_to_resource_service

- app/lib/diff.rb
Add leading `::` and see if it helps with `uninitialized constant SimpleDiff::Diff`: Not sure why we sporadically hit that error, but when we do it's seeing `Diff` as something under `SimpleDiff` rather than as top level. This should fix that.
> Use an absolute rather than relative module path

- app/models/work.rb
This puts the relationship up top and makes it more consistent with the other relationships the work has such as Activities and Files.
> Moving curator to an ActiveRecord relation to make it more consistent with other work relationships

- app/models/pdc_metadata/resource.rb
- app/models/work.rb
- lib/tasks/works.rake
- spec/factories/work.rb
- spec/models/pdc_metadata/resource_spec.rb
- spec/models/pdc_serialization/datacite_spec.rb
- spec/models/work_spec.rb
Allow jsonb metadata field to be actual json, so that is can be queried.
This code still allows for the metadata to be a string in the database also becuase it will parse the string.
fixes #772
> Store metadata as json, not a string blob in a json field

- app/models/work.rb
- lib/tasks/works.rake
fixes #775
refs #772
On staging we can now select the keys of all the works without error:
```
pdc_describe_staging=> select json_object_keys(metadata::json) from works;
json_object_keys    
-----------------------
ark
doi
rights
titles
creators
keywords
award_uri
publisher
description
funder_name
award_number
contributors
resource_type
version_number
collection_tags
related_objects
publication_year
resource_type_general
ark
doi
....
```
On production there are no records:
```
pdc_describe_prod=> select json_object_keys(metadata::json) from works;
json_object_keys 
------------------
(0 rows)
```
> Removing cleanup code for JSON blob in string to actual JSON in postgres jsonb field

- app/assets/stylesheets/application.scss
- app/models/work_activity.rb
- Towards #745:
> Details are available by clicking on the expansion button
Using `<details>` again, since the functionality is similar to the context help.
Screen shot with resource_type collapsed, and rights expanded:
> Show changes fold-down

- app/lib/simple_diff.rb
- spec/lib/diff_spec.rb
Underlying library has strange behavior when given a number. Convert everything to string before diff.
- Fix #788
> Correct display of year in prov log for newly created work

- app/views/works/_related_objects_table.html.erb
- Fix #754
I've also removed "(i.e., published dependencies)" from the label, since that seems to be covered by the longer text.
> Add related objects help text

- spec/factories/work.rb
- spec/models/work_spec.rb
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/migrate_submission_spec.rb
- spec/system/work_spec.rb
- Fix #787
When the issue was originally filed, it seemed like there might be a deeper issue, but I think it's just a naming issue. My guess is that originally `completed` meant that data entry was completed, but it seems to be a source of confusion, so I've renamed to match state, like other fixtures.
```diff
-    factory :completed_work do
+    factory :awaiting_approval_work do
...
state { "awaiting_approval" }
```
> Change test factory name to match state

- app/views/works/show.html.erb
- Towards #746
Fields in order (with fields _italicized_ that were not in mockup, but seemed to belong):
- _Curator_ (= "submitted by"?)
- DOI
- _ARK_
- Creator
- _Contributors_
- Description
- Keywords
- Rights
- Publisher
- Year
- Version
- Resource Type / General Type
The remaining fields are in this order:
- Related Objects
- Collection
- Funder
- Location / Location notes
- Notes
> Rearrange work fields

- app/assets/stylesheets/application.scss
- app/views/works/show.html.erb
- spec/system/work_spec.rb
- Fix #746
I think that this, combined with the reordering of the fields, covers everything that was requested. Tabular layout was not explicitly requested, but I think it makes it more readable, and it it's not wanted, it's in the CSS so it's easy to turn off.
Some small changes to display logic: There is now an "Unspecified" location, if it falls through, and no special formatting is done for "General Type", which is now conditionally displayed.
> Reformat work page with tabular layout / bold labels

- spec/models/pdc_metadata/resource_spec.rb
- spec/rails_helper.rb
I've just run rspec locally twice and both passed; I think two passes in a row would be unlikely for me before this change.
- Fix #804
- To get tests passing, I branched from #805: I suggest reviewing and merging that PR first.
> Tweak webmock configuration for more reliable local rspec runs

- app/models/pdc_serialization/datacite.rb
- Fix #807
Small change in behavior: If an unexpected value were encountered, it would error instead of falling through.
> Simplify logic: use `find_by_value` instead of `elsif` chain

- app/models/s3_file.rb
- app/models/work.rb
- spec/models/s3_file_spec.rb
This just moves the code out of the work into the S3 file, which is where I believe it belongs.
> Moving S3 blob generation into the S3 File to make the work model smaller

- app/models/work_activity.rb
This CSS:
```
.activity-history-item .comment-html {
white-space: pre-wrap;
}
```
means that whitespace is preserved when rendering, including trailing whitespace, which is not what we want.
Before this PR:
After this PR:
> Remove trailing whitespace from message

- app/views/works/review.html.erb
- Fix #764
I believe this is a simple way to do what is needed, though it might not be exactly what was envisioned. Some points to consider:
- It does not add a separate page to the wizard: The provided screenshot has "License" as a step preceding "Complete".
- It does not use a fixed-width font for the license-text, nor does it wrap the license text in a scrollable div, both of which are common in license UIs.
- It does not add license-approval as an extra bit of state in the model: Instead I've just added "Grant License" to the button.
- It also does not give an option to proceed without granting the license, which is an option in the DataSpace screenshot.
- ... so there is no need for this text "Not granting the license will not delete your submission..."
- It only has this sentence …
> Add license text to the last page of the wizard workflow

- app/assets/javascripts/edit_work_utils.js
- app/views/works/_related_objects_table.html.erb
The current placeholder can't actually be read to the end, and we don't include explanatory text in other column headers.
I think the current help text is sufficient, but this is subjective.
after changes, and before:
> Remove redundant help text on Related Identifier

- app/models/work.rb
- app/models/work_state_transition_notification.rb
- config/environments/test.rb
- spec/factories/work.rb
- spec/models/work_spec.rb
- spec/models/work_state_spec.rb
- spec/system/work_create_spec.rb
Moves the code from the Work Model to it's own class WorkStateTransitionNotification
refs #675 
This is related to #831, but it leaves the notification as SYSTEM messages, which means they will show up in the comments/messages section of the work.
This is the smallest change to advance #675 without implementing a Notification screen we do not know if the curators will want.
The only unfortunate part of this change is that the Depositor and the Curators receive the same note. If we sent two different ones then the comments/message section would grow even more.  This may be good enough.  I could see that it would be nice to tell the depositor that this is just a receipt and that no action is required on their part for any of the notifications.
> Sending a notification to the Depositor and the Collection Administrators when state changes occur

- app/assets/stylesheets/application.scss
- app/controllers/works_controller.rb
- app/models/user.rb
- app/models/work.rb
- app/models/work_activity.rb
- app/views/works/_work_activity_history.html.erb
- app/views/works/show.html.erb
- config/routes.rb
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
- spec/requests/works_spec.rb
- Towards #825
"Towards" rather than "Fixes" because of this one line:
```diff
class WorkActivity < ApplicationRecord
...
-  COMMENT = "COMMENT"
+  MESSAGE = "COMMENT" # TODO: Migrate existing records to "MESSAGE"; then close #825.
```
Seems a little bit safer to separate the db migration work from the bulk of the renaming.
There was one odd alias:
```diff
-  alias message_html to_html
```
The `message_html` alias wasn't referenced except for a couple tests, but it would now conflict with the private former `comment_html`, so I got rid of it.
Everything else was just search and replace.
> Find "comment" replace with "message"

- spec/system/data_migration/bitklavier_form_submission_spec.rb
Some of the people for this data set are contributors rather than authors (see original DSpace record https://dataspace.princeton.edu/handle/88435/dsp01nv9356017) and the new spec mimics this.
Part of https://github.com/pulibrary/pdc_discovery/issues/340
> Switched to contributors a few authors in the bitKlavier spec

- README.md
From the conversation in:
- #718
... we identified one necessary piece as the work now in: 
- #839
... but @hhkitsune also [wrote](https://github.com/pulibrary/pdc_describe/issues/718#issuecomment-1348832476)
> I like this statement though and want to see it in our documentation for the repository. It belongs with further detailed description of the migration, rather than in the provenance log.
I don't think an issue was filed for this task, but adding it to the README seems reasonable. Phrasing changed slightly to address the process in general instead of one particular item.
> Add a note to README explaining DataSpace migration

- app/controllers/works_controller.rb
- app/models/work.rb
- app/models/work_activity.rb
- app/views/works/_work_activity_history.html.erb
- config/routes.rb
- spec/controllers/works_controller_spec.rb
- Replace #839
- Fix #720
Notes: 
- User list is hard-coded, as indicated in the issue: I'm the only one on it for now: please add netIDs as needed.
- On the screen we're calling this the "Change History", but I also hear "Provenance" -- It looks like the name "provenance" hasn't really be used in the code before, so I would changes this to "change-history"... unless we should be moving existing references to "provenance"?
- There's no validation of the date string; there could be. The Rails date parsing has some strange behavior:
```
January 12, 2023 00:00 by Chuck
Date was "12"
January 11, 2023 16:35 by Chuck
Date was "1234"
January 11, 2023 00:00 by Chuck
Date was "123"
January 01, 0012 00:00 by Chuck
Date was "12345"
```
> Let admins add free-text, back-dated messages to change-history

- app/controllers/works_controller.rb
- app/models/work.rb
- app/models/work_activity.rb
- app/models/work_state_transition_notification.rb
- app/views/works/_work_activity_history.html.erb
- spec/controllers/works_controller_spec.rb
- spec/models/work_activity_spec.rb
- spec/models/work_spec.rb
- spec/requests/works_spec.rb
- spec/system/work_create_spec.rb
Additionally moving logic for finding the different types of messages into WorkActivity in an effort to make the Work Model smaller.
Also included the title of the work in notifications as I though that would make the emails nicer.
fixes #847
> Moving Notification  on State Change out of the System ActivityType

- app/assets/stylesheets/application.scss
- app/views/works/_work_activity_history.html.erb
- spec/controllers/works_controller_spec.rb
Clean up
- #848 
I don't think we've used client side validation before: I thought this could be a little bit helpful, but it's not essential.
> Add a placeholder and client-side validation to provenance notes

- app/models/work_activity.rb
A little follow-up from https://github.com/pulibrary/pdc_describe/pull/852#discussion_r1069544960
If we have too many similarly named helper methods, I worry that a developer might choose the wrong one by mistake, and get behavior that is only partly correct... but this is just a stylistic change. It's not essential.
> Simplify work_activity by removing underused flag methods

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- spec/models/user_spec.rb
- spec/models/work_activity_notification_spec.rb
- spec/models/work_spec.rb
- spec/system/user_edit_spec.rb
- spec/system/work_comment_spec.rb
Allow Users to recieve emails by default for collection they have deposit rights to Allow users to configure thier emails even when they are not collection administrators Fix bug so that you can uncheck email for specific collections by utilizing the form.check_box instead of the check_box_tag
fixs #762
> Allow collection depositors to receive emails

- spec/system/data_migration/femtosecond_form_submission_spec.rb
- With the latest changes from main merged in, #861 is failing on this test.
- I [had concerns](https://github.com/pulibrary/pdc_describe/pull/878#discussion_r1081324283) about the PR that introduced this test, but approved anyway. That may have been a mistake.
> Disable flakey test

- spec/system/data_migration/femtosecond_form_submission_spec.rb
- Follow up to #883
Locally, the validity check is also failing for me.
> Disable ALL assertions in migration test

- app/models/pdc_metadata/rights.rb
- app/services/resource_compare_service.rb
- spec/services/resource_compare_service_spec.rb
- fix #867
- fix #874 
One caveat: There are form fields that don't populate the resource, ie, notes to curator. I don't think they are in scope, but I could be wrong.
> Show funder changes in log, and refactor `ResourceCompareService` so it will pick up new properties by default

- app/models/work_state_transition_notification.rb
- spec/models/work_state_spec.rb
- Fix #855
- Refactor test to cover four cases: 2 work states (associated with a particular transition method to call) times 2 admin conditions (creator is or is not admin)
> Send just one notification if creator is also admin

- app/models/work.rb
- spec/controllers/works_controller_spec.rb
- Fix #827
I've implemented one exception as suggested in that issue: either ID can be provided without the prefix. I don't know how this feature is being used, so I'm not confident that is the right course.
The test is repetitive: I've tried making it more DRY... but that also makes it harder to read. Whatever the reviewer thinks best: Either approve the current state, or request changes and I could paste it in.
<details><summary>More DRY</summary>
```ruby
describe "ID redirection" do
{
doi: "10.34770/",
ark: "ark:/"
}.each do |method_sym, prefix|
resolve_method_sym = "resolve_#{method_sym}"
describe resolve_method_sym do
before do
sign_in user
stub_s3 data: data
end
let(:data) { [] }
let(:work) { FactoryBot.create(:shakespeare_and_company_work) }
it "redirects to the Work show view" do …
```
> No longer redirect if ARK or DOI is only a partial match (except for the prefix, which is optional)

- README.md
- app/models/work.rb
- spec/models/work_spec.rb
> Adds Globus URL for each file in JSON endpoint

- app/models/domain.rb
- app/models/pdc_metadata/resource.rb
- app/services/form_to_resource_service.rb
- app/views/layouts/application.html.erb
- app/views/works/_additional_form.html.erb
- app/views/works/_domains.html.erb
- app/views/works/show.html.erb
- spec/models/pdc_metadata/resource_spec.rb
- spec/models/work_spec.rb
- spec/services/resource_compare_service_spec.rb
Adds support for a multi-value domain field with a controlled vocabulary in the Additional Metadata section of the Work. 
The current values in the controlled vocabulary were copied from what were using for DataSpace records in PDC Discovery but we could easily expand that list in a future PR once we get the official list from RDOS.
Closes #905
> Adds support for domains

- app/controllers/works_controller.rb
- app/models/work.rb
- app/views/works/show.html.erb
- spec/controllers/works_controller_spec.rb
- spec/factories/work.rb
- spec/system/work_spec.rb
Moved logic for edit button to the work, so it can be utilized in the controller and the view.  The view logic and the controller logic was not quite complete.  The view logic did not care if the user had edit rights for the item.  The controller logic did not allow administrators to edit the work if they submitted the work.
fixes #833
> Allow a curator who deposited a work the ability to edit the work after it has been approved

- spec/models/work_activity_spec.rb
It was moved into the view here https://github.com/pulibrary/pdc_describe/blob/main/app/views/works/_work_activity_messages.html.erb#L6 We should not test the order, just the items returned
> Order is no longer done at the model level

- app/models/work.rb
- spec/factories/work.rb
- spec/models/work_validation_spec.rb
Validation is needed when the record is new, or when the metadata is changed Put the validation into it's own spec file as I would love to move the validation out from the work model and into a spearate class in the future.  Also the work spec files is just too big...
fixes #926
> Updating the Ark validation to only be called when needed

- .circleci/config.yml
Fixes `curl: (22) The requested URL returned error: 404` https://app.circleci.com/pipelines/github/pulibrary/pdc_describe/2644/workflows/f4740255-fb88-48d8-b62a-9bd457992896/jobs/8554
Not sure if we entirely need this.  Rerunning the job caused it to pass.  If CI passes, there does not seem to be any harm in upgrading the ORB though...
> Upgrading browser-tools orb version

- vite.config.ts
Grabbed this technique from Jeff Knox here: https://www.jeffreyknox.dev/blog/dropping-webpack-for-vite-part-2/
On staging we are still minified:
On Development we are not minified:
> Allowing vite javascript to not be minifed in the Development environment

- app/controllers/works_controller.rb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
- app/views/works/file_upload.html.erb
- config/locales/en.yml
- spec/system/authz_admin_spec.rb
- spec/system/authz_submitter_spec.rb
- Fix #943
- Add system tests for flash messages. (Previously, the only tests of flash messages were controller tests... so they didn't fail, even if they didn't make it to the screen.) (Tried for a bit to make a lower-level view test, but never got the wiring sorted out... and view tests aren't our default, in any case.)
- In two cases, we weren't actually sending the right message: fix it.
- Remove redundant rendering of flash messages: It should only be done in one place.
> Test flash messages

- app/models/work.rb
- app/services/s3_query_service.rb
- app/views/works/uploads/_pre_curation_s3_resources.html.erb
- spec/models/s3_file_spec.rb
- spec/models/work_spec.rb
- spec/services/s3_query_service_spec.rb
- spec/support/s3_query_service_specs.rb
- spec/system/view_data_in_s3_spec.rb
- spec/system/work_upload_s3_objects_spec.rb
Displays the number of files in the system and then number of files preserved on the work show page
Memoize file client_s3_files so that we do not make additional calls to S3 for the count 
Memoize the S3 service in the work to make sure we are not creating multiple copies 
Also removed unused methods: url_protocol &  s3_host
fixes #927
> Counting the number of files stored in amazon to allow the user to see system processing progress

- spec/system/data_migration/cklibrary_form_submission_spec.rb
- spec/system/data_migration/sowingseeds_form_submission_spec.rb
Updated the two tests that do not fill in the DOI
fixes #970
> Blanking the migration test DOI so it will be minted on the server when a DOI is not part of the original metadata

- .eslintrc.yaml
- app/assets/javascripts/edit_collection_utils.js
- app/assets/javascripts/edit_work_utils.js
- app/javascript/entrypoints/application.js
- app/javascript/entrypoints/orcid.js
- app/javascript/entrypoints/pdc/copy_to_clipboard.es6
- app/javascript/entrypoints/pdc/maximum_file_upload.es6
- Fix #957
- Explicitly list a couple globals we need for now, but add a TODO with next steps.
- Leave disabled `no-alert`: This seems fine for an application like this that doesn't need a stunning UI, but we could discuss this more.
- Restrict `no-console`: In my experience, adding console.log is a fine debugging tool, but it's useful to have linting that reminds you to clean it up before merging.
- We have one error with `no-restricted-syntax`, but I haven't reproduced the CI behavior locally. Leave it as a TODO.
> Reduce the number of ESLint rules we ignore

- app/controllers/works_controller.rb
- app/models/s3_file.rb
- app/models/work.rb
- app/services/s3_query_service.rb
- app/services/work_uploads_edit_service.rb
- app/views/works/show.html.erb
- app/views/works/uploads/_pre_curation_s3_resources.html.erb
- config/storage.yml
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
- spec/services/s3_query_service_spec.rb
- spec/services/work_upload_edit_service_spec.rb
- spec/support/s3_query_service_specs.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/data_migration/sowingseeds_form_submission_spec.rb
- spec/system/view_data_in_s3_spec.rb
- spec/system/work_comment_spec.rb
- spec/system/work_create_spec.rb
- spec/system/work_edit_spec.rb
- spec/system/work_spec.rb
- spec/system/work_upload_max_spec.rb
- spec/system/work_upload_s3_objects_spec.rb
Re-route the call to always fetch pre-curation files directly from AWS, bypassing ActiveStorage. 
Fixes #941
> Fetch pre-curation files from directly from AWS 

- .circleci/config.yml
- Fix #955
This is slightly more robust: if `.ts` or anything else is included in these directories, it will also be scanned.
I don't see a way to specify the target directories in the `.eslintrc.yaml`, so I think this should close issue.
> ESLint: Scan every file in the directory, instead of listing extensions

- app/controllers/users_controller.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/user.rb
Fixes the problem with the redirect for external net id used in guest accounts (e.g. sometest@gmail.com)
Fixes #993
> Handles external user ids

- app/models/work.rb
- app/services/s3_query_service.rb
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
- spec/requests/works_spec.rb
- spec/services/s3_query_service_spec.rb
- spec/support/s3_query_service_specs.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/migrate_submission_spec.rb
- spec/system/rss_spec.rb
This forced publish to utilize S3 instead of local files, which should be faster. 
Many tests needed to change to not attach files to precuration_uploads and instead mock S3
refs #994
> Removing attach_works which would slow down edits

- app/assets/javascripts/edit_work_utils.js
- app/javascript/entrypoints/application.js
- app/javascript/entrypoints/pdc/edit_required_fields.es6
- app/javascript/entrypoints/pdc/pdc_ui_loader.es6
- app/views/works/_required_creators_table.html.erb
- app/views/works/_required_form.html.erb
- app/views/works/_required_form_field_details.html.erb
- app/views/works/_required_title.html.erb
- spec/system/migrate_submission_spec.rb
- spec/system/work_create_spec.rb
- spec/system/work_edit_spec.rb
Moving required field validation to a Vite class
Adding a Required field partial to make the javascript more consistent
Fixes:
* #999
> Adding javascript validation of the description

- spec/models/pdc_serialization/datacite_spec.rb
- spec/models/upload_snapshot_spec.rb
- spec/models/work_activity_spec.rb
- spec/models/work_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
- spec/support/ark_specs.rb
- spec/system/work_edit_spec.rb
- spec/system/work_show_spec.rb
- spec/system/work_spec.rb
Mock ezid as we are no longer allowing a connection to it during the tests
This [PR](https://github.com/pulibrary/pdc_describe/commit/337f7bb18274e4210ba104691e49fcd13cd6fe3f) disabled webmock, which allowed our tests to be directly connecting to ezid.
Added change to the webmock enable, where it should have gone according [the stack overflow](https://stackoverflow.com/questions/59632283/chromedriver-capybara-too-many-open-files-socket2-for-127-0-0-1-port-951/65946077#65946077) referenced in the original PR.
> Removing call to disable webmock

- spec/models/work_spec.rb
Ruby 3.2+ is going to start requiring an explicit hash when passing named parameters
> Fix deprecation warning

- app/controllers/works_controller.rb
- app/views/works/_required_form.html.erb
- spec/controllers/works_controller_spec.rb
- spec/system/data_migration/attention_form_submission_spec.rb
Makes sure files uploaded are processed when creating a new dataset without using the Wizard.
Closes #1041
I also bundled the fix for #1068 since it was a simple typo in a view.
> Process uploads when creating a dataset outside the wizard

- app/controllers/works_controller.rb
- spec/controllers/works_controller_spec.rb
Files uploaded when creating a new dataset in the wizard were not being processed. @hhkitsune, @neggink, and I noticed this during the last rounds of user testing. 
This PR makes sure these files are processed and uploaded correctly.
> Fixes issue with files uploaded when creating a new dataset in the wizard

- app/controllers/works_controller.rb
- app/decorators/work_decorator.rb
- app/models/work.rb
- app/views/works/_work_activity_messages.html.erb
- app/views/works/_work_activity_provenance.html.erb
- app/views/works/show.html.erb
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
- spec/models/work_state_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/migrate_submission_spec.rb
- spec/system/work_approve_spec.rb
- spec/views/works/work_activity_messages.html.erb_spec.rb
- spec/views/works/work_activity_provenance.html.erb_spec.rb
Also adds decorator for the work to encapsulate the changes and messages, becuase the show can be rendered from the AASM error capture too.
fixes #1036 
FYI it is hard to get to this page now, because the readme will stop the error.  But I went into AWS and removed the files to show the error...
> Requiring files for a work to move to the approved state

- app/assets/stylesheets/application.scss
- app/controllers/work_migration_controller.rb
- app/controllers/works_controller.rb
- app/decorators/work_decorator.rb
- app/models/s3_file.rb
- app/services/form_to_resource_service.rb
- app/services/pul_dspace_data.rb
- app/views/works/_form.html.erb
- app/views/works/show.html.erb
- config/routes.rb
- lib/tasks/dspace.rake
- spec/controllers/works_migration_controller_spec.rb
- spec/decorators/work_decorator_spec.rb
- spec/requests/works_spec.rb
- spec/services/pul_dspace_data_spec.rb
- spec/system/migrate_submission_spec.rb
This is step one for the provenance.  This PR adds the buttons to the UI for running the migration, so that we know who is running the migration.
- Adds migrate file button to work create page to mark the work as being migrated
- Changes edit button on show page to never show the wizard if the file is being migrated
- Adds WorkMigrationController
- Makes small changes to migration to show files and directories separately
refs #1109
New Button on Dataset Creation page
New Button on Show page:
Message for successful migration:
Message when the ark is blank:
> Adding migration button to the Dataset Creation page to migrate content from dspace to pre-curation

- app/views/works/show.html.erb
Displays each related object on a separate line and titlelize the relation types, e.g. "IsCitedBy" becomes "Is Cited By")
Fixes #1013
> Display each related object on a separate line

- db/migrate/20230516133007_role_collection_to_group.rb
- db/schema.rb
fixes #1167 
Worked on production...
```
irb(main):004:0> Role.all
=> 
[#<Role:0x00007fd35f2fa050                                      
id: 1,                                                        
name: "super_admin",                                          
resource_type: nil,                                           
resource_id: nil,                                             
created_at: Wed, 31 Aug 2022 12:55:09.569705000 EDT -04:00,   
updated_at: Wed, 31 Aug 2022 12:55:09.569705000 EDT -04:00>,  
#<Role:0x00007fd35f2f9f88                                      
id: 2,                                                        
name: "submitter",                                            
resource_type: "Collection",                                  
resource_id: 1, …
```
> Adding a database migration to move existing Collection privileges to Group

- app/decorators/work_decorator.rb
- app/models/group.rb
- app/models/work.rb
- app/models/work_list.rb
- app/models/work_state_transition_notification.rb
- app/views/groups/show.html.erb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- app/views/works/_curator_controlled_form.html.erb
- app/views/works/_form.html.erb
- app/views/works/show.html.erb
- db/seeds.rb
- spec/models/group_spec.rb
- spec/system/user_edit_spec.rb
Also moving some comments, ui references, and variables that were still named collection even though a group was being set
> Removing collection method from WorkDecorator

- app/jobs/approved_file_move_job.rb
- app/models/work.rb
- app/services/work_preservation_service.rb
- lib/tasks/works.rake
- spec/jobs/approved_file_copy_job_spec.rb
- spec/services/s3_query_service_spec.rb
- spec/services/work_preservation_service_spec.rb
- spec/support/s3_query_service_specs.rb
Automatically triggers the creation of the preservation metadata once the last file of the work has been moved to the post-curation bucket.
Triggering the code at the right time was trickier than I expected because the work is not marked as "approved" until *after all the actions in the state machine have completed*. The code to create the preservation files is inside the transition, it's the last step, which makes sense, but the state not being completely saved threw me off for a while. 
I had to add a method to the work to force it to fetch post curation files (regardless of the state of the work in the database) because we want to include the file list as part of the preservation metadata and the files at this stage have all been moved to the post-curation bucket.
Closes #512
> Trigger the creation of the preservation once work has been approved

- app/jobs/dspace_file_copy_job.rb
- app/models/migration_upload_snapshot.rb
- app/services/pul_dspace_aws_connector.rb
- app/services/pul_dspace_migrate.rb
- spec/jobs/dspace_file_copy_job_spec.rb
- spec/services/pul_dspace_migrate_spec.rb
If the checksum matches only one file will be uploaded 
If the checksums are different the files will be renamed to show where the duplicates came from and both will be uploaded
Also changed the code that was cloning the s3_files to just put the new AWS filename in the filename_display instead of creating a second copy.  This allowed us to more easily rename the file if needed and should be faster.
fixes #1118
> Remove duplicate uploads for the same file in dspace and AWS

- lib/tasks/works.rake
- spec/models/work_spec.rb
- spec/system/data_migration/cklibrary_form_submission_spec.rb
- spec/system/data_migration/sowingseeds_form_submission_spec.rb
When setting the state to a specific value you do not trigger any of the state transitions.  This is why the doi was not getting set for certain records Also remove the nil setting as it was not needed
refs #1153
> Call draft to trigger state change actions

- .tool-versions
- spec/system/data_migration/attention_form_submission_spec.rb
- spec/system/data_migration/baldwin_form_submission_spec.rb
- spec/system/data_migration/bitklavier_form_submission_spec.rb
- spec/system/data_migration/bitklavierimage_form_submission_spec.rb
- spec/system/data_migration/cklibrary_form_submission_spec.rb
- spec/system/data_migration/cytoskeletal_form_submission_spec.rb
- spec/system/data_migration/design_arrangment_form_submission_spec.rb
- spec/system/data_migration/dynamic_tension_form_submission_spec.rb
- spec/system/data_migration/electromagnetic_form_submission_spec.rb
- spec/system/data_migration/femtosecond_form_submission_spec.rb
- spec/system/data_migration/flume_form_submission_spec.rb
- spec/system/data_migration/fusion_energy_form_submission_spec.rb
- spec/system/data_migration/hybrid_drift_form_submission_spec.rb
- spec/system/data_migration/ion_orbital_form_submission_spec.rb
- spec/system/data_migration/non_axisymmetric_form_submission_spec.rb
- spec/system/data_migration/observation_axisymmetric_form_submission_spec.rb
- spec/system/data_migration/sowingseeds_form_submission_spec.rb
- spec/system/data_migration/spindle_form_submission_spec.rb
- spec/system/data_migration/thomson_scattering_form_submission_spec.rb
This makes sure the edit goes to the non wizard version and the `Migrate Dataspace Files` button is present when the json is imported
> Changing specs to use the new migrate button

- app/controllers/users_controller.rb
- app/models/user.rb
- app/models/work_activity.rb
- app/views/groups/_dataset_table.html.erb
- app/views/groups/show.html.erb
- app/views/notification_mailer/build_message.html.erb
- app/views/notification_mailer/build_message.text.erb
- app/views/users/_dataset_table.html.erb
- app/views/users/_form.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- app/views/welcome/index.html.erb
- app/views/works/_form_hidden_fields.html.erb
- app/views/works/_orcid_link.html.erb
- app/views/works/show.html.erb
- db/migrate/20230524181606_user_display_name_to_given_name.rb
- db/schema.rb
- spec/factories/user.rb
- spec/mailers/notification_mailer_spec.rb
- spec/models/user_spec.rb
- spec/requests/welcome_spec.rb
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/user_edit_spec.rb
- spec/system/work_approve_spec.rb
- spec/system/work_create_spec.rb
We have been using the display name as the given name in the system.  This PR updates the database field name and all calls to it to given_name so there is no confusion about it in the future
> Updating display name in the user to be given name

- app/javascript/entrypoints/pdc/edit_required_fields.es6
- spec/system/work_create_spec.rb
When the user is on the Additional metadata tab, but does not fill out the required fields we want the screen to switch back to the required field tab so the user can see why the save is not working
> Making sure the user can see the required error messages when editing the work

- app/views/works/_orcid_link.html.erb
- app/views/works/_organization_link.html.erb
- app/views/works/_ror_link.html.erb
- app/views/works/show.html.erb
Moving ROR icon to the end of the url per [guidelines](https://ror.readme.io/docs/ror-id-display-guidelines-and-logos#inline-ror-id)
Also, moved organizational ROR to a partial specifically for the organization link and then used the ror_link partial to be a reusable partial for an ROR link
refs #959
> Displaying Affiliation and ROR on the show page of the work for the creator

- app/controllers/works_controller.rb
- app/views/works/new_submission.html.erb
- spec/controllers/works_controller_spec.rb
This allows the javascript to fail and the user to see a real error vs an exception fixes #1196
> Capturing AASM errors during the new_submission action

- app/javascript/entrypoints/pdc/work_orcid.es6
- spec/support/external_identifier_specs.rb
Forces the request to the ORCID API to pass `application/json` on the HTTP headers. This fixes the problem where a few requests return a response that jQuery cannot parse -- even though the majority of the calls work OK with the previous configuration using JSONP via `dataType: 'jsonp'`
Closes #1271
> Fixes issue fetching ORCID values

- app/models/user.rb
- spec/models/user_spec.rb
Make sure the last name (family name) is set when importing users from a CSV file.
Closes #1272
> Set last name when importing users

- app/views/works/_s3_resources.html.erb
- spec/system/view_data_in_s3_spec.rb
> Adding target=_blank to download link so that the page remains in the correct spot

- README.md
- app/services/pul_dspace_connector.rb
- spec/services/pul_dspace_migrate_spec.rb
Fixes #1273 
Co-authored-by: Carolyn Cole <carolyncole@users.noreply.github.com>
> Use Base64 encoded MD5 checksum as required by updated AWS S3 API

- app/views/works/_related_objects_table.html.erb
- app/views/works/_required_form.html.erb
Removes HTML placeholders that we misleading or redundant.
Closes #1288
Closes #1287
> Remove misleading placeholders 

- app/services/work_preservation_service.rb
- spec/services/work_preservation_service_spec.rb
Added the provenance information to the files that we create during preservation. This information includes the user entered messages and also the history of changes to the metadata on the record.
I also added an option to save the preservation files locally (rather than always saving them on S3). This was not part of the original request but it is really handy to have this option and use it via the original rake task:
```
$ bundle exec rake works:preserve[1,localhost,preservation_test/1]
file:///Users/correah/src/pdc_describe/preservation_test/1/princeton_data_commons/
```
Closes #1214
> Include provenance information in preservation files

- app/javascript/entrypoints/pdc/readme_file_upload.es6
- app/views/works/readme_select.html.erb
- spec/fixtures/files/readme.txt
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/external_ids_spec.rb
- spec/system/work_create_spec.rb
Configures the upload file in the browser to limit the files that a user can select as a readme to only those with extensions `txt` or `md` and also validates that the file selected has the word "readme" somewhere in the name (case insensitive.)
We validate the actual name of the file via JavaScript because we cannot make the name restriction directly on the Browser Dialog.
Closes #1139
> Validate the name of the uploaded readme file

- app/javascript/entrypoints/pdc/pdc_ui_loader.es6
- app/javascript/entrypoints/pdc/work_edit_file_upload.es6
- app/views/works/_form.html.erb
Updated the message to make it clear to the user which files they are adding. 
I added some extra functionality via JavaScript to list the specific files selected. By default the browser displays the name of the file to upload *when it is only one file*, when more than one file is selected (say 3) it just displays "3 files selected". With the new JavaScript it always list the names of the files to upload and therefore it should be clear(er) to the user what they are doing.
Closes #1157
> Update messaging when uploading files during edit

- app/views/notification_mailer/build_message.html.erb
- app/views/notification_mailer/build_message.text.erb
- spec/mailers/notification_mailer_spec.rb
This causes the html in the message to be displayed as parsed html instead of straight html text 
Also updated the wording to be a bit less repetitive 
fixes #1165
Original notification format:
New Format after PR:
> Updating the notification email to make the message html safe

- app/models/work.rb
Also remove comment about pre_curation_uploads being different, becuase now that we are using pre_curation_uploads_fast they are the same
> Removing unused method add_pre_curation_s3_object

- app/controllers/works_controller.rb
- spec/controllers/works_controller_spec.rb
The old format was still being done for the check to not allow files to be deleted on approved works.  Since the UI does not allow edits on approved works this was not tested in a system test.  When I added the expectation to the test for delete_s3_object to have been called I noticed the bug in the test, which lead me to the bug in the code
> Moving the controller to utilize the new deleted_file_* format

- app/controllers/works_controller.rb
- spec/controllers/works_controller_spec.rb
I introduced this bug when I changed the work_params to not just automatically return all params. I believe it does make more sense to utilze the method that returns the uploads in this case though...
> Fixing the missing uploads when adding files via the wizard

- app/controllers/works_controller.rb
- app/models/readme.rb
- app/services/s3_query_service.rb
- spec/models/readme_spec.rb
- spec/support/s3_query_service_specs.rb
This allows the readme to be show as uploaded by the correct user 
Had to change the model to allow for the current_user to be passed in 
Also needed access to the checksum from the S3 upload so added a last response attribute onto the S3QueryService
refs #1329
> Adding an UploadSnapshot to the readme process

- app/decorators/work_decorator.rb
- spec/decorators/work_decorator_spec.rb
> Ensure that group administrators who are non-depositor users for any given Work are still authorized to mark the Work as complete

- app/controllers/work_migration_controller.rb
- app/services/pul_dspace_migrate.rb
- spec/controllers/works_migration_controller_spec.rb
- spec/services/pul_dspace_migrate_spec.rb
> Move the WorkActivity::MIGRATION_START to before the dspace migration so that it can be completed successfully if there are no globus files

- app/services/work_preservation_service.rb
- spec/services/work_preservation_service_spec.rb
Makes sure the preservation files are not included as part of the metadata used for preservation.
Closes #1362
> Make sure preservation files are not includes in the preservation metadata 

- app/jobs/attach_file_to_work_job.rb
- app/models/background_upload_snapshot.rb
- app/models/work.rb
- app/services/work_uploads_edit_service.rb
- spec/controllers/works_controller_spec.rb
- spec/models/background_upload_snapshot_spec.rb
- spec/requests/works_spec.rb
- spec/services/work_upload_edit_service_spec.rb
Tied it into WorkUploadsEditService and AttachFileToWork job to make the additions occur in a single activity
Additionally fixed the bug where the temp file gets deleted before the background job can process it: `Error performing AttachFileToWorkJob (Job ID: 342410b4-b9bb-4b04-b0f6-3a2ca2747c6c) from Inline(default) in 397.6ms: ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError)`
The above error was being created when the temp file was unlinked before it could be attached.
See https://pdc-describe-staging.princeton.edu/describe/works/439 for a successful run in which all files uploaded attached and got marked as being attached by me...
> Added a BackgroundUploadSnapshot to link all the uploaded files to a single activity

- app/views/works/_form_hidden_fields.html.erb
- app/views/works/_required_form.html.erb
- spec/system/work_edit_spec.rb
refs #1325
Although we would not expect the administrator to blank the DOI, we would expect the administrator to have the ability to set the DOI to a new value.  The DOI being show on another part of the form was overriding the DOI on the curator controlled metadata form
> Allow the Group Administrator to set the DOI

- config/provenance_message_writers.yml
Closes #1341 
Per conversation with Hannah in a meeting this morning, this feature should be hidden from curators/moderators while we are making https://github.com/pulibrary/pdc_describe/issues/1336 workable, but we should remove staff no longer here, and should allow visibility within RDSS.
> Updated provenance writers list

- app/controllers/works_controller.rb
- app/views/shared/_user_actions.html.erb
- app/views/works/_form.html.erb
- app/views/works/new.html.erb
- spec/system/data_migration/attention_form_submission_spec.rb
- spec/system/data_migration/baldwin_form_submission_spec.rb
- spec/system/data_migration/bitklavier_form_submission_spec.rb
- spec/system/data_migration/bitklavierimage_form_submission_spec.rb
- spec/system/data_migration/cklibrary_form_submission_spec.rb
- spec/system/data_migration/cytoskeletal_form_submission_spec.rb
- spec/system/data_migration/design_arrangment_form_submission_spec.rb
- spec/system/data_migration/dynamic_tension_form_submission_spec.rb
- spec/system/data_migration/electromagnetic_form_submission_spec.rb
- spec/system/data_migration/femtosecond_form_submission_spec.rb
- spec/system/data_migration/flume_form_submission_spec.rb
- spec/system/data_migration/fusion_energy_form_submission_spec.rb
- spec/system/data_migration/hybrid_drift_form_submission_spec.rb
- spec/system/data_migration/ion_orbital_form_submission_spec.rb
- spec/system/data_migration/non_axisymmetric_form_submission_spec.rb
- spec/system/data_migration/observation_axisymmetric_form_submission_spec.rb
- spec/system/data_migration/sowingseeds_form_submission_spec.rb
- spec/system/data_migration/spindle_form_submission_spec.rb
- spec/system/data_migration/thomson_scattering_form_submission_spec.rb
- spec/system/migrate_submission_spec.rb
Introducing two modes for new Datasets: creation and migration. This ensures that uses who access the new Dataset form using the migration mode are forced to migrate from an existing Dataset resource.
Advances #1396, as @carolyncole has identified that users may be unknowingly trigger this behavior should they unintentionally overlook the proper `Migrate` button on the form.
> Introduces a "Migration" mode for new Datasets

- app/services/s3_query_service.rb
- spec/services/s3_query_service_spec.rb
When a nil was returned that passed through the if check on the key and the error that occured when uploading a large file was logged, but missed by the code
> Make sure the error gets noted by returning false

- app/controllers/users_controller.rb
- app/models/group.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- db/migrate/20230810125820_add_enabled_and_subcommunity_to_group_option.rb
- db/schema.rb
- spec/models/group_spec.rb
- spec/models/user_spec.rb
- spec/models/work_activity_notification_spec.rb
- spec/requests/users_spec.rb
- spec/system/user_edit_spec.rb
- spec/system/work_comment_spec.rb
This allows us to default to true if nothing is found. 
Also added the sub-community field to the database so we can turn the group options on and off for a sub-community too in a later PR
refs #1383
> Updating the database to store if a user enables or disables group messaging

- app/assets/stylesheets/application.scss
- app/controllers/users_controller.rb
- app/javascript/entrypoints/pdc/email_change_all.es6
- app/javascript/entrypoints/pdc/pdc_ui_loader.es6
- app/models/group.rb
- app/models/work_activity_notification.rb
- app/views/users/_form.html.erb
- spec/models/work_activity_notification_spec.rb
- spec/system/user_edit_spec.rb
Javascript to check and uncheck all email checkboxes
A user must explicitly disable a subcommunity, as all emails a by default on until explicitly disabled
refs #1383
> A UI to allow a user to choose which PPPL subcommunities are enabled for email

- app/models/work.rb
- app/views/works/show.html.erb
- spec/system/work_show_spec.rb
This will let us more easily check whether the work has yet appeared in PDC Discovery, separate from whether the ARK and DOI redirection have worked as expected.
Ref #1399
> Show the PDC Discovery url on the work show page

- app/controllers/works_controller.rb
- app/views/shared/_user_actions.html.erb
- spec/system/data_migration/attention_form_submission_spec.rb
- spec/system/data_migration/baldwin_form_submission_spec.rb
- spec/system/data_migration/bitklavier_form_submission_spec.rb
- spec/system/data_migration/bitklavierimage_form_submission_spec.rb
- spec/system/data_migration/cklibrary_form_submission_spec.rb
- spec/system/data_migration/cytoskeletal_form_submission_spec.rb
- spec/system/data_migration/design_arrangment_form_submission_spec.rb
- spec/system/data_migration/dynamic_tension_form_submission_spec.rb
- spec/system/data_migration/electromagnetic_form_submission_spec.rb
- spec/system/data_migration/femtosecond_form_submission_spec.rb
- spec/system/data_migration/flume_form_submission_spec.rb
- spec/system/migrate_submission_spec.rb
This allows the migrator to determine which group the item is migrating to before starting the form. Then there is not a need to change the group in the form because it is already set.
fixes #1439
> Adding group to the Migrate Dataset menu link

- app/services/pul_dspace_migrate.rb
- spec/services/pul_dspace_migrate_spec.rb
stop the mysterious 10-34770/ directories in AWS
fixes #1409
> Changing the directory to match with the DOI

- app/services/pul_dspace_connector.rb
- spec/services/pul_dspace_connector_spec.rb
- spec/services/pul_dspace_migrate_spec.rb
- spec/system/migrate_submission_spec.rb
This will ignore the license and extracted text
fixes #1452
> Only migrate the dspace files from the ORIGINAL bundle

- app/jobs/dspace_bitstream_copy_job.rb
- app/models/migration_upload_snapshot.rb
- spec/jobs/dspace_bitstream_copy_job_spec.rb
- spec/models/migration_upload_snapshot_spec.rb
Because of the status check for "started" or "error" in find file, the `complete?` method was never returning true 
Also checks the filename_display for dspace files as those are the only ones that will match. The /tmp/dspace... will never match the s3 file location
fixes #1478
> Making the migration snapshot check for completed files correct

- app/javascript/entrypoints/application.js
This was discovered while advancing #1491
> Removing errors related to the ActiveStorage JavaScript library (this is not used)

- config/environments/development.rb
This was discovered while advancing #1491
> Ensuring that the SCSS templates are not cached for the `development` environment

- app/models/work.rb
- spec/models/work_spec.rb
This is required in order to ensure that PDC Discovery can index the embargo dates into the Solr Documents. Advances #1491
> Ensuring that the JSON-serialized Works render the embargo dates in the ISO 8601 format

- app/models/work_activity_notification.rb
from this [stack overflow](https://stackoverflow.com/questions/40672232/activejobdeserializationerror-error-while-trying-to-deserialize-arguments) we are adding a wait to send the mail a bit later after we are sure postgres will have comitted the changes refs #1504
Mail is still being sent with this update:
> Following recommendation to send mail just a bit later

- app/jobs/dspace_bitstream_copy_job.rb
- app/models/migration_upload_snapshot.rb
- app/models/work_activity_notification.rb
- app/services/file_rename_mapping_service.rb
- app/services/file_rename_service.rb
- spec/factories/migration_upload_snapshot.rb
- spec/services/file_rename_mapping_service_spec.rb
- spec/services/file_rename_service_spec.rb
Fixes #1512 
Co-authored-by: Carolyn Cole <carolyncole@users.noreply.github.com>
- Rename files with S3 illegal characters to something that is S3 legal by replacing all illegal characters with a _ (underscore)
- Ensure there are no duplicate file names after the renaming by appending a (1), (2) at the end of the filename if the file has been renamed
- Keep a record of all of the file names as they originally existed and what they were renamed to
- The record goes into a file called files_renamed.txt, which contains a list of all files that have been renamed and what they were renamed to, along with a date.
- This files_renamed.txt file gets added to the dataset as a payload file
- Update the migration upload snapshot so it doesn't get confused about the files now having different names
> Rename files with S3 illegal characters

- .circleci/config.yml
- Gemfile
- Gemfile.lock
I thought parallelizing the tests was going to be an easy win for faster CI. I am sorely disappointed.
> Remove test parallelizing until it works

- Gemfile
These were in production early in the project because we were using them to generate test data. No longer needed except in test.
Fixes https://github.com/pulibrary/pdc_describe/issues/147
> Move testing gems to test environment

- app/models/work_activity.rb
This will also allow us to reuse the group and markdown processing in other renders
> Updating the BaseMessage rendered to not have a rubocop violation

- db/migrate/20231025155725_provenance_note_format.rb
- db/schema.rb
Before the migration ran there was an error with a work that had the old format
After the migration ran the work loads correctly
fixes #1546
> Adding migration for work activity provenance notes to new format

- app/models/s3_file.rb
- app/services/s3_query_service.rb
- spec/services/s3_query_service_spec.rb
refs #1580
Should allow us to see if there are any empty files when we transfer files on approval.
> Adding a method to discover empty files to the s3query service

- app/services/s3_query_service.rb
- spec/fixtures/s3_list_bucket_empty_result.xml
- spec/services/s3_query_service_spec.rb
> Ensuring that empty S3 files are not moved between S3 Buckets when a Work is published

- config/deploy.rb
refs https://github.com/pulibrary/orcid_princeton/issues/57
> Sharing node_modules directory between deploys to make yarn install faster

- spec/services/resource_compare_service_spec.rb
This will also make the test run faster because it won't write to the database
Fixes #1592
> Use build instead of create to avoid ARK collision

- config/deploy.rb
@tpendragon pointed out [this issue](https://github.com/capistrano/npm/issues/7).  We are not doing an npm install, but that occurs when we do a asset:precompile so we are doing that task on rollback.
Also needed to clear `deploy:assets:restore_manifest` becuase we are no longer utilizing sprokets
> Allow asset compile on a capistrano roll back

- app/models/version_footer.rb
Did not notice the file was hard coded to the spec
On this branch
```
irb(main):001:0> VersionFooter.log_line(Rails.root.join("..", "..", "revisions.log"))
=> "Branch main (at 4bd241ac537a93da81ccd49a4c6ce0c76b5a8670) deployed as release 20231106141433 by colec"
```
On Main branch
```
irb(main):003:0> VersionFooter.log_line(Rails.root.join("..", "..", "revisions.log"))
=> nil
```
> Fixing bug introduced by the rollback PR

- architecture-decisions/0013-preservation-s3-bucket.md
We decided that we do not want to replicate deletion markers between the main bucket and Amazon S3 
This has already been implemented in Amazon S3
fixes #1618
> Update the preservation ADR to reflect our change to the Deletion marker replication

- .rubocop.yml
- app/jobs/approved_file_move_job.rb
- spec/jobs/approved_file_copy_job_spec.rb
This is meant to improve error logging in order to advance #1607
> Restructures the ApprovedFileMoveJob error logging for cases in which the ApprovedUploadSnapshot cannot be resolved

- app/controllers/works_controller.rb
- app/jobs/update_snapshot_job.rb
- config/sidekiq.yml
- spec/jobs/update_snapshot_job_spec.rb
- spec/requests/works_spec.rb
This should allow the page to display for very large sets of files and the prvenance to be updated later
Also putting this job on it's own queue since it could take a very long time we do not want it subverting other jobs
refs #1621
> Moving work reload_snapshot from the show to a background job

- app/models/work.rb
- app/services/s3_query_service.rb
- app/views/works/_s3_resources.html.erb
- app/views/works/show.html.erb
- spec/services/s3_query_service_spec.rb
- spec/support/s3_query_service_specs.rb
- spec/system/provenance_note_spec.rb
Note I am showing the number of files and directories in AWS vs just the number of files. I think having that total number will help to compare between AWS and the UI.  With small numbers of files that are not in a directory structure the number of files and the number of directories is the same.  With complex data like that number can be far off and be disconcerting. 
I found 3 theoretical ways to count the files.  The first is the way in this PR, the second is via the aws command line, and the third is our current approach.  I counted the 1.4 Million files in the dspace bucket in the 3 ways. The new way in this PR took about half the time.  Not great since it is a little less than 6 minutes, but better than 10
```
[5] pry(main)> start_dateTime = DateTime.now; puts …
```
> Adding a method to just count the files instead of fully processing them

- app/javascript/entrypoints/pdc/edit_required_fields.es6
- spec/system/work_create_spec.rb
- spec/system/work_edit_spec.rb
Also fixes a bug in the test, which is filling in the Family name and the expecting it to also be blank.  This no longer occurs because we are ignoring empty rows, but did occur in the past because the empty row was causing the family name issue.
fixes #1628
> Allow empty row in the creator and contributor tables to be ignored

- app/services/s3_query_service.rb
- spec/services/s3_query_service_spec.rb
It turns out the response for the AWS bucket listing always include the bucket as the first response Updated the fake response to reflect that fact and then updated the code to ignore that entry.
fixes #1651
`Aws::S3::Types::Object key="10.34770/tbd/1/"` is the bucket in the response below:
```
[
#<struct Aws::S3::Types::Object key="10.34770/tbd/1/", last_modified=2023-09-19 19:48:45 UTC, etag="\"d41d8cd98f00b204e9800998ecf8427e\"", checksum_algorithm=[], size=0, storage_class="STANDARD", owner=nil>, 
#<struct Aws::S3::Types::Object key="10.34770/tbd/1/Copy of HTML _ Accessibility Checkpoint Project.docx", last_modified=2023-10-23 18:32:28 UTC, etag="\"91010724f6b805fd2d1952c8e263f799\"", checksum_algorithm=[], size=93342, storage_class="STANDARD", owner=nil>, 
#<struct …
```
> Ignoring the bucket in the AWS Key count

- app/controllers/groups_controller.rb
- app/models/group.rb
- app/models/user.rb
- spec/models/group_spec.rb
- spec/system/authz_admin_spec.rb
> Setting the user's default group to the current group when they are created as a submitter

- app/decorators/work_decorator.rb
Added a work-around to get the file-list URL working in stating and production
Fixes #1704 (but does not quite close it)
> Fixed file-list URL in staging and production

- app/controllers/works_controller.rb
- config/routes.rb
- spec/controllers/works_controller_spec.rb
The option was removed from the wizard.  We should also remove it from the controller
> Removing controller action for file cluster

- app/decorators/work_decorator.rb
(This fixes an urgent bug in production related to https://github.com/pulibrary/pdc_describe/issues/1665#issuecomment-2012430189)
> Ensures that download URLs for Work assets prepend the "/describe" path

- app/assets/stylesheets/application.scss
- app/controllers/works_wizard_controller.rb
- app/services/work_metadata_service.rb
- app/views/works_wizard/new_submission.html.erb
- config/routes.rb
- spec/controllers/works_wizard_controller_spec.rb
This was more complex than expected, because some times the work is persisted and sometimes not now that we can stay on the page.
For this reason I extracted some code into the WorkMetadataService.
The new button:
#1684
> Allowing the new submission form to save and stay on page

- app/controllers/works_controller.rb
- app/views/layouts/application.html.erb
- app/views/works/_form.html.erb
- config/routes.rb
Integrates Uppy to handle file uploads in the Work edit screen (i.e. not in the Wizard)
Closes #1685 forward
Notice that Uppy is only used if we pass the `new_uploader=true` as a query string parameter. I am going to use this to demo the functionality to Matt.
There are a couple of additional tickets to implement this in the Wizard too: https://github.com/pulibrary/pdc_describe/issues/1731 and https://github.com/pulibrary/pdc_describe/issues/1732
> Uses Uppy for uploads in the Work edit screen

- app/controllers/application_controller.rb
- app/controllers/works_update_additional_controller.rb
- app/controllers/works_wizard_controller.rb
- app/views/works/_form.html.erb
- app/views/works/_form_metadata.html.erb
- app/views/works/_form_nav.html.erb
- app/views/works_update_additional/_form_wizard.html.erb
- app/views/works_update_additional/update_additional.html.erb
- app/views/works_wizard/_form_wizard.html.erb
- app/views/works_wizard/edit_wizard.html.erb
- app/views/works_wizard/readme_select.html.erb
- app/views/works_wizard/update_additional.html.erb
- config/routes.rb
- spec/controllers/works_update_additonal_controller_spec.rb
- spec/controllers/works_wizard_controller_spec.rb
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/external_ids_spec.rb
- spec/system/pppl_work_create_spec.rb
- spec/system/work_create_spec.rb
- spec/system/work_wizard_reverse_spec.rb
- spec/system/work_wizard_spec.rb
fixes #1684 
Adds variables to the form partials to either show the required metadata tab first or the additional metadata tab first.
Updates the tests that walk through the system to hit next on the Additional metadata screen
> Adds the additional step to the wizard that takes you to the Additional Metadata portion of the form

- app/controllers/wizard_policy_controller.rb
- app/controllers/works_wizard_controller.rb
- app/services/work_metadata_service.rb
- app/views/users/show.html.erb
- app/views/wizard_policy/show.html.erb
- config/routes.rb
- spec/controllers/wizard_policy_controller_spec.rb
- spec/controllers/works_wizard_controller_spec.rb
- spec/factories/work.rb
- spec/system/authz_submitter_spec.rb
- spec/system/authz_super_admin_spec.rb
- spec/system/external_ids_spec.rb
- spec/system/pppl_work_create_spec.rb
- spec/system/work_create_spec.rb
- spec/system/work_spec.rb
- spec/system/work_wizard_spec.rb
Big change for the rest of the code is that the work is expected to exists before the new-submission page.
This is the only way we can attach a Provenance note that indicates the agreement was selected.
fixes #1688
> Adding a new page to the front of the wizard

- app/views/works/show.html.erb
- spec/system/authz_super_admin_spec.rb
- spec/system/migrate_submission_spec.rb
- spec/system/work_approve_spec.rb
Display warning dialog before approving a work. Takes into account works with embargoes.
Closes #1650
> Display confirm dialog before approving a work

- app/controllers/works_controller.rb
- app/controllers/works_wizard_controller.rb
- app/models/readme.rb
- app/models/work.rb
- app/services/work_uploads_edit_service.rb
- app/views/works_wizard/file_upload.html.erb
- config/routes.rb
- spec/services/work_upload_edit_service_spec.rb
Uploading files added via the Wizard right away (instead of as a background job). This fixes the display issue reported in #1760. 
I also added Rails route to handle the Upload of files on the Wizard (instead of using the Upload process from the Work controller) as described in https://github.com/pulibrary/pdc_describe/issues/1757
The new code introduces a bug in the way we generate the UploadSnapshots, though. See below:
> Fixes Wizard delay in displaying uploaded files

- app/views/wizard_policy/show.html.erb
Disable the "Confirm" button until user clicks on the checkbox to agree to the New Submission Policy
> Disable the Confirm button until user agrees to the new submission policy

- app/models/readme.rb
- spec/models/readme_spec.rb
Allows for back and forth movement in the wizard and the correct update of the provenance log
fixes #1766
> Updating the readme to allow for existing files for provenance

- app/services/s3_query_service.rb
- config/s3.yml
Since we are moving away from ActiveStorage::Blob we moved our configuration values out of the Rails `storage.yml` file into our own `s3.yml` file. Technically we copied the values from one config to the other, we have not deleted `storage.yml`
The reason for this is that Rails was failing to automagically load values from `storage.yml` now that we are not loading the ActiveStorage:Blob classes (see https://github.com/pulibrary/pdc_describe/pull/1775 for more information on that) and it made sense to stop putting the values in a Rails file that Rails is not using.
> Updating configuration to work in local dev environments

- app/mailers/notification_mailer.rb
- app/models/work.rb
- app/models/work_state_transition_notification.rb
Temporary work-around to fix and troubleshoot bad Work URLs generated in some places.
In some instances Rails is adding an extra `/describe` to the Work URLs and we end up with links that go do `/describe/describe/`. See details in #1783
I believe this issue only happens when the call to `Rails.application.routes.url_helpers` to generate the `work_url` hapens outside of the Views or the Controllers (e.g. in the models, in our mailers).
And of course this only happens in production ¯\_(ツ)_/¯ 
I suspect this issue was introduced when we set `Rails.application.routes.default_url_options[:relative_url_root] = "/describe"` (see PR https://github.com/pulibrary/pdc_describe/pull/1733) but I suspect that *that PR* also fixed the weird redirect issue described in …
> Fixes and logs bad Work URLs in production

- app/models/readme.rb
- spec/models/readme_spec.rb
Closes #1782 
Updates the code to not rename the README file anymore.
> Preserves user's README file name

- config/initializers/number_to_human_size_converter.rb
- spec/models/s3_file_spec.rb
- spec/system/work_upload_s3_objects_spec.rb
Closes #1793 
Rails does not specify a parameter to allow us to specify a specific base. So, we override the function to allow us to specify a base which by default is now 1000 instead of 1024.
> Switch to use gigabytes instead of gigibytes

- app/views/users/_dataset_table.html.erb
- spec/system/work_wizard_spec.rb
Displays the record as "untitled" and forces the user back to the wizard.
Closes #1802
> Handles abandoned works in the wizard

- README.md
- config/deploy.rb
This allows us to see how a specific server looks without having to go through the load balancer
> Allow capistrano to open up the application on the servers

- app/models/s3_file.rb
- app/models/work.rb
- app/services/pul_dspace_aws_connector.rb
- app/services/s3_query_service.rb
- app/views/works/_s3_resources.html.erb
- spec/services/pul_dspace_aws_connector_spec.rb
- spec/services/s3_query_service_spec.rb
Updated the code to display empty file names and empty folders on the file list.
This prevents the issue where the file count displayed to the user does not match the number of files on the list.
We made empty files and empty folders not downloadables on the file list.
Below is an example of how these empty files/folders are displayed:
Closes #1826 
Closes #1784
See also https://github.com/pulibrary/pdc_describe/issues/1836
> Fixes file count discrepancy

- app/assets/javascripts/edit_work_utils.js
- spec/system/work_edit_spec.rb
Fixes the display issue when deleting a file **and** the file count of deleted file too.
Closes #1833 
Closes #1835
Issue #1834 is not fixed with this PR. That will be handled separately.
> Fixes display issue when deleting a file

- app/models/background_upload_snapshot.rb
- app/services/work_uploads_edit_service.rb
- spec/services/work_upload_edit_service_spec.rb
Logs the correct provenance (who deleted the file) when deleting a file via the Edit screen:
Closes #1834
> Fixes the bad provenance logged when deleting files

- app/models/user.rb
- db/migrate/20240705120614_safe_uid.rb
- db/schema.rb
- spec/controllers/omniauth_callbacks_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/user.rb
- spec/models/user_spec.rb
- spec/system/user_show_spec.rb
external uids are the entire email, so we need to make them safe
Also makes all existing uids in the database safe via migration
fixes https://github.com/pulibrary/pdc_describe/issues/1823
> Making the UID not include unsafe characters for routing

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
I am also experiencing a strange `Coveralls` error where including `Coveralls.wear!` triggers an error. I am attempting to test this commit first and confirm that Coveralls is still receiving reports.
> Ensuring the SimpleCov utilizes the HTML formatter for local development environments

- app/services/s3_query_service.rb
- spec/services/s3_query_service_spec.rb
Turns out you need to url encode the key if you put it with the bucket name. 
'bucket/key+with+space' needs to be 'bucket/key%2Bwith%2Bspace' for copy_object 
even though aws will tell you the key is 'key+with+space'
fixes #1874
> uri encoding the source key in dataspace file copy

- app/assets/stylesheets/application.scss
fixes #1868
Note:  Datatable will resize properly with a reload, but not with a change of the window.
> Allow urls to wrap and setup widths on description list to be responsive

- app/controllers/users_controller.rb
- app/views/users/_form.html.erb
- spec/system/user_edit_spec.rb
Allows a user to edit their own email address and an administrator (or moderator) to adjust the default group for another user. Both of these values need to be tweaked for GAP accounts and this PR allows users to manually adjust the values without needing a developer to fix the data.
Closes #1901 
Closes #1905
> User edit improvements

- app/models/background_upload_snapshot.rb
- app/models/work.rb
- app/models/work_activity.rb
- app/models/work_state_transition_notification.rb
- spec/models/background_upload_snapshot_spec.rb
Advances #1919 by ensuring that errors (and a warning) are logged in order to capture what led to the errors in the production environment
> Ensures that empty files and nil user IDs for WorkActivity objects raise ArgumentErrors

- app/controllers/work_migration_controller.rb
- spec/system/accessibility_spec.rb
Resolves #510 by changing the accessibility test in accessibility_spec.rb#L56-68 to use FactoryBot.create(:distinct_cytoskeletal_proteins_work)).
> Change accessibility test to use real data

- config/initializers/health_monitor.rb
We had more than 20k and that was normal for a large work
> Upping the number of items that can be in the sidekiq queue

- app/decorators/work_decorator.rb
- app/models/work.rb
- app/models/work_activity.rb
- app/views/works/_work_activity_provenance.html.erb
- lib/tasks/works.rake
Addresses the issue of loading a work with a large number of messages in the provenance log. 
The culprit was two fold:
1. The code to mark notifications as read iterates one by one on each notification which translates on individual SQL SELECT commands. This PR batches the SQL UPDATE which is much faster, particularly when there are thousand of notifications in the database.
2. There is also a problem with the way we determine the user name to display for each notification. The code issues a SQL SELECT for each notification to retrieve the user name to display (in addition to the user's netid). Even with Rails using its internal cache this is slow when there are thousands of SYSTEM generated notifications. This PR displays only the first 100 SYSTEM notifications and let's the user know …
> Fixes time out issue on records with very large number of provenance messages

- app/assets/stylesheets/components/header.scss
- app/views/welcome/index.html.erb
Closes #2003 
I used the [WebAIM color contrast tool and selected this combination for accessibility](https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=595959).
> Adjusted color contrast and fixed a typo

- spec/system/work_wizard_spec.rb
Fixes the flaky test for the Work Wizard.
I am not entirely sure how come this test passed sometimes but not others. If I am reading the spec correctly *it should had always failed* since (1) it does not add a data file to the work (it only adds the readme) and (2) the very last check for the "title" should always fail given that we don't display the file on the last step. ¯_(ツ)_/¯
Closes #2002
> Fixes flaky test

- app/jobs/approved_file_move_job.rb
- spec/jobs/approved_file_copy_job_spec.rb
Checks if the file has already moved before throwing an error
> Add a catch for Aws::S3::Errors::NoSuchKey error

- config/initializers/health_monitor.rb
- config/initializers/redis_config.rb
- config/initializers/sidekiq_config.rb
- config/redis.yml
We were not configuring sidekiq correctly to allow a remote redis
> Allow redis to be remote based on the redis url

- architecture-decisions/0016-file-list-size.md
Documents file size limitations in PDC Describe 
https://github.com/pulibrary/pdc_discovery/pull/773 documented them for PDC Discovery.
> ADR for file size size limitations

- app/services/pul_cache.rb
- config/initializers/health_monitor.rb
Copied @carolyncole 's implementation of the Redis cache (https://github.com/pulibrary/pdc_describe/pull/2056) to workaround the bug in the default HealthMonitor check.
Closes #2014
> Adds a custom health check for the Rails cache

- app/views/welcome/index.html.erb
- spec/system/reports_dataset_spec.rb
The My Reports page takes too long to load by default because it's fetching data for all years. Changed the default to start with datasets for this year only (which loads relatively quickly). The user still can select "all years" in the drop down if they are interested in a wider range.
Related to https://github.com/pulibrary/pdc_describe/issues/2028
> Default My Reports to show datasets for the current year

- app/services/pul_redis.rb
We are seeing so many less now.  How about a slightly larger random key https://app.honeybadger.io/projects/99214/faults/115631944
> Make the Redis health check random number seed larger so we do not collide

- app/controllers/application_controller.rb
- app/controllers/works_controller.rb
- app/controllers/works_wizard_controller.rb
- app/views/works/_form_hidden_fields.html.erb
- spec/controllers/works_controller_spec.rb
This does not fix the bug where funder information was removed during an update but *it will* help us determine if when saving a dataset the data will overwrite data written before. 
If we determine that the problem is users stepping on each other (or even the same user with two browser windows open over writting their own changes) we can decide how to handle this (e.g. warn a user that they will overwrite some changes)
Part of #1925 
This is an example of a Honeybadger entry for this kind of situation: https://app.honeybadger.io/projects/99214/faults/118747777
> Logs if a dataset updates will overwrite previous updates

- Gemfile.lock
error 'uninitialized constant Capistrano::SCM::Git::StringIO (NameError)' when deploying main
For some reason ansible tower still worked just fine...
> Update Capistrano to fix issue deploying

- app/models/work.rb
- spec/models/work_spec.rb
released are approved works with an embargo day of yesterday 
embargoed are currently embargoed today or in the future
Standardized the functions to use sql current_date function.
> Adds a method to find released embargo in a standard fashion

- app/controllers/work_downloader_controller.rb
- app/controllers/works_controller.rb
- app/jobs/approved_file_move_job.rb
- app/models/work.rb
- app/services/s3_query_service.rb
- app/services/work_preservation_service.rb
- app/views/works/_s3_resources.html.erb
- docs/how_to_delete_a_work.md
- lib/tasks/works.rake
- spec/controllers/works_controller_spec.rb
- spec/models/work_spec.rb
Moves files to the the embargo bucket (instead of post-curation) for embargoed works.
Closes #2055 
> Move files to embargo bucket for approved embargoed works

- app/models/group.rb
- app/models/user.rb
- spec/models/group_spec.rb
Prevent adding users without emails and triggering database constraint errors.
Closes #2107
> Fixes problem adding submitters that are not Users

- lib/tasks/works.rake
Adds a rake task to output the data in our UploadSnapshots to get a view of what happened to the files uploaded to a work. This will help us see what was added and deleted and when.
Part of #2121
> Rake task to output file snapshots for a work
